/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package otros;

import java.awt.Event;
import java.awt.event.KeyEvent;
import javax.swing.*;


public class dialogNuevoProveedor extends javax.swing.JDialog {
Proveedor proveedorclase = new Proveedor();    
SQLProveedor sqlproveedor = new SQLProveedor();

Icon iconoAlerta  =  new ImageIcon("C:/Sistema Muninn/Imagenes/alertaIcono.png");
Icon iconoBueno  =  new ImageIcon("C:/Sistema Muninn/Imagenes/aceptadoIcono.png");
Icon iconoError  =  new ImageIcon("C:/Sistema Muninn/Imagenes//errorIcono.png");
Icon iconoInfo  =  new ImageIcon("C:/Sistema Muninn/Imagenes/infoIcono.png"); 
//  ,"Notificación", JOptionPane.PLAIN_MESSAGE, iconoError);


    public dialogNuevoProveedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtProvWebS = new javax.swing.JTextField();
        txtProvEmail = new javax.swing.JTextField();
        txtProvCiud = new javax.swing.JTextField();
        txtProvDir = new javax.swing.JTextField();
        txtProvFono = new javax.swing.JTextField();
        txtProvNomb = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btAgregarInform = new javax.swing.JButton();
        btAgregarInform1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MUNINN - Agregar información de un Nuevo Proveedor");
        setMaximumSize(new java.awt.Dimension(740, 455));
        setMinimumSize(new java.awt.Dimension(740, 455));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(217, 230, 217));
        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.setOpaque(false);

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel6.setText("Sitio Web");

        txtProvWebS.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtProvWebS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtProvWebSKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtProvWebSKeyTyped(evt);
            }
        });

        txtProvEmail.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtProvEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtProvEmailKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtProvEmailKeyTyped(evt);
            }
        });

        txtProvCiud.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtProvCiud.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtProvCiudKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtProvCiudKeyTyped(evt);
            }
        });

        txtProvDir.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtProvDir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtProvDirKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtProvDirKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtProvDirKeyTyped(evt);
            }
        });

        txtProvFono.setBackground(new java.awt.Color(255, 255, 204));
        txtProvFono.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtProvFono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtProvFonoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtProvFonoKeyTyped(evt);
            }
        });

        txtProvNomb.setBackground(new java.awt.Color(255, 255, 204));
        txtProvNomb.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtProvNomb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtProvNombKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtProvNombKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel1.setText("Nombre del Proveedor*");

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel3.setText("Telefono*");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("Dirección");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setText("Ciudad");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel5.setText("Correo Electronico");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtProvFono, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProvNomb)
                    .addComponent(txtProvCiud)
                    .addComponent(txtProvDir)
                    .addComponent(txtProvEmail)
                    .addComponent(txtProvWebS, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtProvNomb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtProvFono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtProvDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtProvCiud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtProvEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtProvWebS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 129, 720, 210);

        btAgregarInform.setBackground(new java.awt.Color(95, 107, 95));
        btAgregarInform.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btAgregarInform.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoNuevo.png"))); // NOI18N
        btAgregarInform.setText("     Agregar información");
        btAgregarInform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarInformActionPerformed(evt);
            }
        });
        getContentPane().add(btAgregarInform);
        btAgregarInform.setBounds(100, 350, 361, 49);

        btAgregarInform1.setBackground(new java.awt.Color(95, 107, 95));
        btAgregarInform1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btAgregarInform1.setText("Cancelar");
        btAgregarInform1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarInform1ActionPerformed(evt);
            }
        });
        getContentPane().add(btAgregarInform1);
        btAgregarInform1.setBounds(520, 350, 190, 47);

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonAddProveedor.png"))); // NOI18N
        jLabel8.setText("Agregar Información de Nuevo Proveedor ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(142, 11, 519, 100);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoProveedores.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 780, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAgregarInformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarInformActionPerformed
     
    String nombrprov = txtProvNomb.getText(); 
    
    String verificaprov = sqlproveedor.existeProveedor(nombrprov); 
          
    if(verificaprov.equals(""))
    {
        if(validarProv())
        {              

            String tfonocl = txtProvFono.getText();
            int telefno= Integer.parseInt(tfonocl);

            //Conversion a mayuscula
            
            String nombreprov = txtProvNomb.getText();
            nombreprov = nombreprov.toUpperCase();
            
            String dirprov = txtProvDir.getText();
            dirprov = dirprov.toUpperCase();
            
            String ciudprov = txtProvCiud.getText();
            ciudprov = ciudprov.toUpperCase();
            
            String emailprov = txtProvEmail.getText();
            emailprov = emailprov.toUpperCase();
            
            String websiteprov = txtProvWebS.getText();
            websiteprov = websiteprov.toUpperCase();
            
            proveedorclase.setNombre_proveedor(nombreprov);
            proveedorclase.setDireccion_proveedor(dirprov);   
            proveedorclase.setTelefono_proveedor(telefno);
            proveedorclase.setCiudad_proveedor(ciudprov);
            proveedorclase.setEmail_proveedor(emailprov);
            proveedorclase.setSitioweb_proveedor(websiteprov);
                        
            sqlproveedor.agregarProveedor(proveedorclase);
            int mensaje= JOptionPane.showConfirmDialog(rootPane, "Proveedor Agregado con Exito \n ¿Desea agregar otra Proveedor?", "\tConfirmación",
            JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,iconoAlerta);

     if(mensaje==JOptionPane.YES_NO_OPTION)
            {
            txtProvNomb.setText("");
            txtProvDir.setText("");
            txtProvFono.setText("");
            txtProvCiud.getText();
            txtProvEmail.setText("");
            txtProvWebS.setText("");
            }

        else{
            
            this.dispose();
            }
            
            
            
            
            
        }
    }
    else
    {   
        System.out.print("ERROR El proveedor ya existe\n");
        JOptionPane.showMessageDialog(rootPane, "El Proveedor ya esta registrado","Notificación", JOptionPane.PLAIN_MESSAGE, iconoError);
    }    
        
    }//GEN-LAST:event_btAgregarInformActionPerformed

    private void txtProvFonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProvFonoKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c) == false) {
            evt.consume();
        }
        if(txtProvFono.getText().length()== 9) {
            evt.consume();
        }
    }//GEN-LAST:event_txtProvFonoKeyTyped

    private void txtProvNombKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProvNombKeyTyped
        if(txtProvNomb.getText().length()== 45) {
            evt.consume();
        }
    }//GEN-LAST:event_txtProvNombKeyTyped

    private void txtProvDirKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProvDirKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProvDirKeyReleased

    private void txtProvDirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProvDirKeyTyped
        if(txtProvDir.getText().length()== 45) {
            evt.consume();
        }
    }//GEN-LAST:event_txtProvDirKeyTyped

    private void txtProvCiudKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProvCiudKeyTyped
        if(txtProvCiud.getText().length()== 45) {
            evt.consume();
        }
    }//GEN-LAST:event_txtProvCiudKeyTyped

    private void txtProvEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProvEmailKeyTyped
        if(txtProvEmail.getText().length()== 45) {
            evt.consume();
        }
    }//GEN-LAST:event_txtProvEmailKeyTyped

    private void txtProvWebSKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProvWebSKeyTyped
        if(txtProvWebS.getText().length()== 45) {
            evt.consume();
        }
    }//GEN-LAST:event_txtProvWebSKeyTyped

    private void btAgregarInform1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarInform1ActionPerformed
        int mensaje= JOptionPane.showConfirmDialog(rootPane, "Todos los Cambios no guardados se perderan \n ¿Confirma cancelar?", "\tConfirmación",
            JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,iconoAlerta);

     if(mensaje==JOptionPane.YES_NO_OPTION)
            {
                this.dispose();
            }
    }//GEN-LAST:event_btAgregarInform1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int mensaje= JOptionPane.showConfirmDialog(rootPane, "Atención: Todos los cambios no Guardados se perderan\n¿Confirma Cerrar esta ventana??", 
                        "\tCerrar", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
                if(mensaje==JOptionPane.YES_NO_OPTION)
                {
                    this.dispose();
                }
    }//GEN-LAST:event_formWindowClosing

    private void txtProvNombKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProvNombKeyPressed
InputMap map2 =  txtProvNomb.getInputMap( txtProvNomb.WHEN_FOCUSED);
      map2.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");         // TODO add your handling code here:
    }//GEN-LAST:event_txtProvNombKeyPressed

    private void txtProvFonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProvFonoKeyPressed
InputMap map2 = txtProvFono.getInputMap(txtProvFono.WHEN_FOCUSED);
      map2.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");         // TODO add your handling code here:
    }//GEN-LAST:event_txtProvFonoKeyPressed

    private void txtProvDirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProvDirKeyPressed
InputMap map2 = txtProvDir.getInputMap(txtProvDir.WHEN_FOCUSED);
      map2.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");         // TODO add your handling code here:
    }//GEN-LAST:event_txtProvDirKeyPressed

    private void txtProvCiudKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProvCiudKeyPressed
InputMap map2 = txtProvCiud.getInputMap(txtProvCiud.WHEN_FOCUSED);
      map2.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");         // TODO add your handling code here:
    }//GEN-LAST:event_txtProvCiudKeyPressed

    private void txtProvEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProvEmailKeyPressed
InputMap map2 = txtProvEmail.getInputMap(txtProvEmail.WHEN_FOCUSED);
      map2.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");         // TODO add your handling code here:
    }//GEN-LAST:event_txtProvEmailKeyPressed

    private void txtProvWebSKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProvWebSKeyPressed
InputMap map2 = txtProvWebS.getInputMap(txtProvWebS.WHEN_FOCUSED);
      map2.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");         // TODO add your handling code here:
    }//GEN-LAST:event_txtProvWebSKeyPressed

 
public boolean validarProv()
    {
    
    boolean respuesta=true;
    String variable1 = "";
    
    if(txtProvNomb.getText().equals(""))
                {
                variable1= variable1 + "Debe ingresar el Nombre del Proveedor\n";
                txtProvNomb.requestFocus();
                respuesta=false;
                }
    else if(txtProvFono.getText().equals(""))
                {
                variable1= variable1 + "Debe ingresar el Numero Telefonico del Proveedor\n";
                txtProvNomb.requestFocus();
                respuesta=false;
                }
     if(!respuesta)
    {
      JOptionPane.showMessageDialog(rootPane, variable1, "Notificación", JOptionPane.PLAIN_MESSAGE, iconoAlerta);
        }
    return respuesta;
    }    
    
    
    
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dialogNuevoProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dialogNuevoProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dialogNuevoProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dialogNuevoProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                dialogNuevoProveedor dialog = new dialogNuevoProveedor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAgregarInform;
    private javax.swing.JButton btAgregarInform1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtProvCiud;
    private javax.swing.JTextField txtProvDir;
    private javax.swing.JTextField txtProvEmail;
    private javax.swing.JTextField txtProvFono;
    private javax.swing.JTextField txtProvNomb;
    private javax.swing.JTextField txtProvWebS;
    // End of variables declaration//GEN-END:variables
}
