/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package productos;

import java.awt.Event;
import java.awt.event.KeyEvent;
import javax.swing.*;
import otros.Proveedor;
import otros.SQLProveedor;


public class dialogNuevoProveedorProd extends javax.swing.JDialog {
Proveedor proveedorclase = new Proveedor();    
SQLProveedor sqlproveedor = new SQLProveedor();

Icon iconoAlerta  =  new ImageIcon("C:/Sistema Muninn/Imagenes/alertaIcono.png");
Icon iconoBueno  =  new ImageIcon("C:/Sistema Muninn/Imagenes/aceptadoIcono.png");
Icon iconoError  =  new ImageIcon("C:/Sistema Muninn/Imagenes//errorIcono.png");
Icon iconoInfo  =  new ImageIcon("C:/Sistema Muninn/Imagenes/infoIcono.png");   



    public dialogNuevoProveedorProd(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btAgregarInform1 = new javax.swing.JButton();
        btAgregarInform = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtProvWebS = new javax.swing.JTextField();
        txtProvEmail = new javax.swing.JTextField();
        txtProvCiud = new javax.swing.JTextField();
        txtProvDir = new javax.swing.JTextField();
        txtProvFono = new javax.swing.JTextField();
        txtProvNomb = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MUNINN -  Nuevo Proveedor");
        setMaximumSize(new java.awt.Dimension(904, 395));
        setMinimumSize(new java.awt.Dimension(904, 395));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(217, 230, 217));
        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.setLayout(null);

        btAgregarInform1.setBackground(new java.awt.Color(95, 107, 95));
        btAgregarInform1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btAgregarInform1.setText("Cancelar");
        btAgregarInform1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarInform1ActionPerformed(evt);
            }
        });
        jPanel2.add(btAgregarInform1);
        btAgregarInform1.setBounds(610, 300, 180, 49);

        btAgregarInform.setBackground(new java.awt.Color(95, 107, 95));
        btAgregarInform.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btAgregarInform.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoNuevo.png"))); // NOI18N
        btAgregarInform.setText("     Agregar información");
        btAgregarInform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarInformActionPerformed(evt);
            }
        });
        jPanel2.add(btAgregarInform);
        btAgregarInform.setBounds(80, 300, 500, 49);

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonAddProveedor.png"))); // NOI18N
        jLabel8.setText("Agregar Información de Nuevo Proveedor ");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(200, 0, 519, 100);

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel6.setText("Sitio Web");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(90, 260, 53, 17);

        txtProvWebS.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtProvWebS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtProvWebSKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtProvWebSKeyTyped(evt);
            }
        });
        jPanel2.add(txtProvWebS);
        txtProvWebS.setBounds(240, 260, 549, 30);

        txtProvEmail.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtProvEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtProvEmailKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtProvEmailKeyTyped(evt);
            }
        });
        jPanel2.add(txtProvEmail);
        txtProvEmail.setBounds(240, 230, 549, 30);

        txtProvCiud.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtProvCiud.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtProvCiudKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtProvCiudKeyTyped(evt);
            }
        });
        jPanel2.add(txtProvCiud);
        txtProvCiud.setBounds(240, 200, 549, 30);

        txtProvDir.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtProvDir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtProvDirKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtProvDirKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtProvDirKeyTyped(evt);
            }
        });
        jPanel2.add(txtProvDir);
        txtProvDir.setBounds(240, 170, 549, 30);

        txtProvFono.setBackground(new java.awt.Color(255, 255, 204));
        txtProvFono.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtProvFono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtProvFonoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtProvFonoKeyTyped(evt);
            }
        });
        jPanel2.add(txtProvFono);
        txtProvFono.setBounds(240, 140, 163, 30);

        txtProvNomb.setBackground(new java.awt.Color(255, 255, 204));
        txtProvNomb.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtProvNomb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtProvNombKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtProvNombKeyTyped(evt);
            }
        });
        jPanel2.add(txtProvNomb);
        txtProvNomb.setBounds(240, 110, 549, 30);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel1.setText("Nombre del Proveedor*");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(90, 120, 141, 17);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel3.setText("Telefono*");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(90, 140, 59, 17);

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("Dirección");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(90, 170, 53, 17);

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setText("Ciudad");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(90, 200, 38, 17);

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel5.setText("Correo Electronico");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(90, 230, 104, 17);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoProveedores.png"))); // NOI18N
        jPanel2.add(jLabel7);
        jLabel7.setBounds(-10, -40, 980, 520);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 904, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAgregarInformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarInformActionPerformed
     
    String nombrprov = txtProvNomb.getText(); 
    
    String verificaprov = sqlproveedor.existeProveedor(nombrprov); 
          
    if(verificaprov.equals(""))
    {
        if(validarProv())
        {              

            String tfonocl = txtProvFono.getText();
            int telefno= Integer.parseInt(tfonocl);

            //Conversion a mayuscula
            
            String nombreprov = txtProvNomb.getText();
            nombreprov = nombreprov.toUpperCase();
            
            String dirprov = txtProvDir.getText();
            dirprov = dirprov.toUpperCase();
            
            String ciudprov = txtProvCiud.getText();
            ciudprov = ciudprov.toUpperCase();
            
            String emailprov = txtProvEmail.getText();
            emailprov = emailprov.toUpperCase();
            
            String websiteprov = txtProvWebS.getText();
            websiteprov = websiteprov.toUpperCase();
            
            proveedorclase.setNombre_proveedor(nombreprov);
            proveedorclase.setDireccion_proveedor(dirprov);   
            proveedorclase.setTelefono_proveedor(telefno);
            proveedorclase.setCiudad_proveedor(ciudprov);
            proveedorclase.setEmail_proveedor(emailprov);
            proveedorclase.setSitioweb_proveedor(websiteprov);
                        
            sqlproveedor.agregarProveedor(proveedorclase);
            JOptionPane.showMessageDialog(rootPane,"La información del Proveedor fue agregada con exito",  "Notificación", JOptionPane.PLAIN_MESSAGE, iconoBueno);
            this.dispose();
            
        }
    }
    else
    {   
        System.out.print("ERROR El proveedor ya existe\n");
        JOptionPane.showMessageDialog(rootPane, "El Proveedor ingresado ya se encuentra registrado", "Notificación", JOptionPane.PLAIN_MESSAGE, iconoAlerta);
    }    
        
    }//GEN-LAST:event_btAgregarInformActionPerformed

    private void txtProvFonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProvFonoKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c) == false) {
            evt.consume();
        }
        if(txtProvFono.getText().length()== 9) {
            evt.consume();
        }
    }//GEN-LAST:event_txtProvFonoKeyTyped

    private void txtProvNombKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProvNombKeyTyped
        if(txtProvNomb.getText().length()== 45) {
            evt.consume();
        }
    }//GEN-LAST:event_txtProvNombKeyTyped

    private void txtProvDirKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProvDirKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProvDirKeyReleased

    private void txtProvDirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProvDirKeyTyped
        if(txtProvDir.getText().length()== 45) {
            evt.consume();
        }
    }//GEN-LAST:event_txtProvDirKeyTyped

    private void txtProvCiudKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProvCiudKeyTyped
        if(txtProvCiud.getText().length()== 45) {
            evt.consume();
        }
    }//GEN-LAST:event_txtProvCiudKeyTyped

    private void txtProvEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProvEmailKeyTyped
        if(txtProvEmail.getText().length()== 45) {
            evt.consume();
        }
    }//GEN-LAST:event_txtProvEmailKeyTyped

    private void txtProvWebSKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProvWebSKeyTyped
        if(txtProvWebS.getText().length()== 45) {
            evt.consume();
        }
    }//GEN-LAST:event_txtProvWebSKeyTyped

    private void btAgregarInform1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarInform1ActionPerformed
        int mensaje= JOptionPane.showConfirmDialog(rootPane, " ¿Confirma Cancelar esta operación? \n Todos los cambios sin guardar se Perderan", "\tConfirmación",
    JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE, iconoAlerta);

     if(mensaje==JOptionPane.YES_NO_OPTION)
            {
            this.dispose();
            }
    }//GEN-LAST:event_btAgregarInform1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int mensaje= JOptionPane.showConfirmDialog(rootPane, "Atención: Todos los cambios no Guardados se perderan\n¿Confirma Cerrar esta ventana??", 
                        "\tCerrar", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
                if(mensaje==JOptionPane.YES_NO_OPTION)
                {
                    this.dispose();
                }
    }//GEN-LAST:event_formWindowClosing

    private void txtProvNombKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProvNombKeyPressed
InputMap map2 =  txtProvNomb.getInputMap( txtProvNomb.WHEN_FOCUSED);
      map2.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null"); 
    }//GEN-LAST:event_txtProvNombKeyPressed

    private void txtProvFonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProvFonoKeyPressed
InputMap map2 =  txtProvFono.getInputMap( txtProvFono.WHEN_FOCUSED);
      map2.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");         // TODO add your handling code here:
    }//GEN-LAST:event_txtProvFonoKeyPressed

    private void txtProvDirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProvDirKeyPressed
InputMap map2 =  txtProvDir.getInputMap( txtProvDir.WHEN_FOCUSED);
      map2.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");         // TODO add your handling code here:
    }//GEN-LAST:event_txtProvDirKeyPressed

    private void txtProvCiudKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProvCiudKeyPressed
InputMap map2 =  txtProvCiud.getInputMap( txtProvCiud.WHEN_FOCUSED);
      map2.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");         // TODO add your handling code here:
    }//GEN-LAST:event_txtProvCiudKeyPressed

    private void txtProvEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProvEmailKeyPressed
InputMap map2 =  txtProvEmail.getInputMap( txtProvEmail.WHEN_FOCUSED);
      map2.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");         // TODO add your handling code here:
    }//GEN-LAST:event_txtProvEmailKeyPressed

    private void txtProvWebSKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProvWebSKeyPressed
InputMap map2 =  txtProvWebS.getInputMap( txtProvWebS.WHEN_FOCUSED);
      map2.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");         // TODO add your handling code here:
    }//GEN-LAST:event_txtProvWebSKeyPressed

 
public boolean validarProv()
    {
    
    boolean respuesta=true;
    String variable1 = "";
    
    if(txtProvNomb.getText().equals(""))
                {
                variable1= variable1 + "Debe ingresar el Nombre del Proveedor\n";
                txtProvNomb.requestFocus();
                respuesta=false;
                }
    else if(txtProvFono.getText().equals(""))
                {
                variable1= variable1 + "Debe ingresar el Numero Telefonico del Proveedor\n";
                txtProvNomb.requestFocus();
                respuesta=false;
                }
     if(!respuesta)
    {
      JOptionPane.showMessageDialog(rootPane, variable1, "Notificación", JOptionPane.PLAIN_MESSAGE, iconoAlerta);
        }
    return respuesta;
    }    
    
    
    
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dialogNuevoProveedorProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dialogNuevoProveedorProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dialogNuevoProveedorProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dialogNuevoProveedorProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                dialogNuevoProveedorProd dialog = new dialogNuevoProveedorProd(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAgregarInform;
    private javax.swing.JButton btAgregarInform1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtProvCiud;
    private javax.swing.JTextField txtProvDir;
    private javax.swing.JTextField txtProvEmail;
    private javax.swing.JTextField txtProvFono;
    private javax.swing.JTextField txtProvNomb;
    private javax.swing.JTextField txtProvWebS;
    // End of variables declaration//GEN-END:variables
}
