/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package productos;

import arriendos.dialogAgregarProdArr;
import inicio.inicioRapido;
import java.awt.Color;
import java.awt.Event;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import otros.Categoria;
import otros.Proveedor;
import otros.dialogNuevoProveedor;

public class dialogNuevoProducto extends javax.swing.JDialog {
    
SQLProducto sqlproducto = new SQLProducto();    
Producto productoclase = new Producto();
Categoria categoriaclase = new Categoria();
Proveedor proveedorclase = new Proveedor();

Icon iconoAlerta  =  new ImageIcon("C:/Sistema Muninn/Imagenes/alertaIcono.png");
Icon iconoBueno  =  new ImageIcon("C:/Sistema Muninn/Imagenes/aceptadoIcono.png");
Icon iconoError  =  new ImageIcon("C:/Sistema Muninn/Imagenes//errorIcono.png");
Icon iconoInfo  =  new ImageIcon("C:/Sistema Muninn/Imagenes/infoIcono.png"); 

    public dialogNuevoProducto(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BuscadorFoto = new javax.swing.JFileChooser();
        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btExaminar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtArchivo = new javax.swing.JTextField();
        txtDirectorio = new javax.swing.JTextField();
        txtRuta = new javax.swing.JTextField();
        lbVistaPrevia = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textDescrp = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        txtMarcaProd = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPUnitArr = new javax.swing.JTextField();
        txtAddClDig1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listProveedor = new javax.swing.JList();
        btAddProveedor = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listCategorias = new javax.swing.JList();
        btAddCategoria = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtCostUnitC = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btAddProd = new javax.swing.JButton();
        btAddProd1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MUNINN -  Nuevo Producto");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagenes/miniLogo.png")).getImage());
        setMaximumSize(null);
        setMinimumSize(null);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(null);

        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.setOpaque(false);

        btExaminar.setBackground(new java.awt.Color(51, 51, 51));
        btExaminar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btExaminar.setForeground(new java.awt.Color(255, 255, 255));
        btExaminar.setText("Examinar...");
        btExaminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExaminarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Adjuntar Imagen");

        jPanel4.setBackground(new java.awt.Color(217, 215, 198));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setMaximumSize(new java.awt.Dimension(151, 98));
        jPanel4.setOpaque(false);

        jLabel15.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Nombre del Archivo");

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Directorio");

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Ruta");

        txtArchivo.setBackground(new java.awt.Color(204, 204, 204));
        txtArchivo.setEditable(false);
        txtArchivo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtArchivo.setMaximumSize(new java.awt.Dimension(6, 20));

        txtDirectorio.setBackground(new java.awt.Color(204, 204, 204));
        txtDirectorio.setEditable(false);
        txtDirectorio.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtDirectorio.setMaximumSize(new java.awt.Dimension(6, 20));

        txtRuta.setBackground(new java.awt.Color(204, 204, 204));
        txtRuta.setEditable(false);
        txtRuta.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtRuta.setMaximumSize(new java.awt.Dimension(6, 20));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel13)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDirectorio, javax.swing.GroupLayout.DEFAULT_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtDirectorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbVistaPrevia.setBackground(new java.awt.Color(255, 255, 204));
        lbVistaPrevia.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbVistaPrevia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lbVistaPrevia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btExaminar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btExaminar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbVistaPrevia, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel3);
        jPanel3.setBounds(10, 10, 380, 470);

        jPanel1.setBackground(new java.awt.Color(221, 219, 197));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Descripción*");

        textDescrp.setBackground(new java.awt.Color(255, 255, 204));
        textDescrp.setColumns(20);
        textDescrp.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        textDescrp.setRows(5);
        textDescrp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textDescrpKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textDescrpKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textDescrpKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(textDescrp);

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Marca*");

        txtMarcaProd.setBackground(new java.awt.Color(255, 255, 204));
        txtMarcaProd.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtMarcaProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMarcaProdKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMarcaProdKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMarcaProdKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cantidad a Ingresar");

        txtCantidad.setBackground(new java.awt.Color(255, 255, 204));
        txtCantidad.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCantidadKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCantidadKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Costo Unit de Arriendo por Hora*");

        txtPUnitArr.setBackground(new java.awt.Color(255, 255, 204));
        txtPUnitArr.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtPUnitArr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPUnitArrKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPUnitArrKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPUnitArrKeyTyped(evt);
            }
        });

        txtAddClDig1.setBackground(new java.awt.Color(255, 255, 204));
        txtAddClDig1.setEditable(false);
        txtAddClDig1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        txtAddClDig1.setText("* Campos Obligatorios");
        txtAddClDig1.setBorder(null);
        txtAddClDig1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAddClDig1KeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Proveedor *");

        listProveedor.setBackground(new java.awt.Color(255, 255, 204));
        listProveedor.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listProveedorMouseClicked(evt);
            }
        });
        listProveedor.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listProveedorValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(listProveedor);

        btAddProveedor.setBackground(new java.awt.Color(51, 51, 51));
        btAddProveedor.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btAddProveedor.setForeground(new java.awt.Color(255, 255, 255));
        btAddProveedor.setText("Agregar un Proveedor");
        btAddProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddProveedorActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Categoria *");

        listCategorias.setBackground(new java.awt.Color(255, 255, 204));
        listCategorias.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listCategorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listCategoriasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listCategorias);

        btAddCategoria.setBackground(new java.awt.Color(51, 51, 51));
        btAddCategoria.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btAddCategoria.setForeground(new java.awt.Color(255, 255, 255));
        btAddCategoria.setText("Agregar una Categoria");
        btAddCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddCategoriaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Costo Unitario por Compra*");

        txtCostUnitC.setBackground(new java.awt.Color(255, 255, 204));
        txtCostUnitC.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtCostUnitC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCostUnitCKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCostUnitCKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCostUnitCKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtMarcaProd, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCostUnitC, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtPUnitArr, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(txtAddClDig1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(8, 8, 8))
                            .addComponent(jLabel8))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(btAddProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btAddCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAddProveedor)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btAddCategoria)
                        .addGap(31, 31, 31))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAddClDig1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtMarcaProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCostUnitC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtPUnitArr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(jLabel8)
                                .addContainerGap())))))
        );

        jPanel6.add(jPanel1);
        jPanel1.setBounds(400, 10, 720, 320);

        jPanel2.setBackground(new java.awt.Color(140, 13, 13));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoProducto2.png"))); // NOI18N
        jLabel11.setText("Nuevo Producto");

        btAddProd.setBackground(new java.awt.Color(51, 51, 51));
        btAddProd.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        btAddProd.setForeground(new java.awt.Color(255, 255, 255));
        btAddProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoProductomininuevo.png"))); // NOI18N
        btAddProd.setText("Agregar Producto");
        btAddProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddProdActionPerformed(evt);
            }
        });

        btAddProd1.setBackground(new java.awt.Color(51, 51, 51));
        btAddProd1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        btAddProd1.setForeground(new java.awt.Color(255, 255, 255));
        btAddProd1.setText("Cerrar Ventana");
        btAddProd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddProd1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btAddProd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAddProd1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btAddProd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAddProd1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel11)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel2);
        jPanel2.setBounds(400, 350, 720, 128);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoProductos.png"))); // NOI18N
        jPanel6.add(jLabel6);
        jLabel6.setBounds(0, 0, 1180, 520);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 1173, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btExaminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExaminarActionPerformed
    FileNameExtensionFilter filtro=new FileNameExtensionFilter ("JPG", "JPEG", "jpg", "jpeg");
    File  ruta;
    BuscadorFoto.setApproveButtonText("Abrir Archivo");
    BuscadorFoto.setDialogTitle("Abrir Archivo...");
    BuscadorFoto.setFileFilter(filtro);
    //BuscadorFoto.showDialog(this, null);
    
       
    int status = BuscadorFoto.showOpenDialog(null);// Da un entero
    // Si apretamos en aceptar ocurrirá esto
    if (status == JFileChooser.APPROVE_OPTION) 
    {
       // File selectedFile = BuscadorFoto.getSelectedFile();
        //System.out.println(selectedFile.getParent());
        ruta=BuscadorFoto.getSelectedFile();//ruta + archivo
        String directorio=String.valueOf(BuscadorFoto.getCurrentDirectory());
        String archivo=BuscadorFoto.getName(ruta);//nombre archivo
        
        txtRuta.setText(String.valueOf(ruta)); 
        txtDirectorio.setText(String.valueOf(directorio));
        txtArchivo.setText(archivo);
        
        ImageIcon foto=new ImageIcon(txtRuta.getText());
        Icon icono=new ImageIcon(foto.getImage().getScaledInstance(lbVistaPrevia.getWidth(), lbVistaPrevia.getHeight(),Image.SCALE_DEFAULT));
        lbVistaPrevia.setIcon(icono);
        
    // Si apretamos en cancelar o cerramos la ventana ocurrirá esto
    } else if (status == JFileChooser.CANCEL_OPTION) {
        txtRuta.setText("");
        txtDirectorio.setText("");
        txtArchivo.setText("");

        ImageIcon foto2=new ImageIcon("");
        Icon icono=new ImageIcon(foto2.getImage().getScaledInstance(lbVistaPrevia.getWidth(), lbVistaPrevia.getHeight(),Image.SCALE_DEFAULT));
        lbVistaPrevia.setIcon(icono);
        
        
        
    }
    

        
    }//GEN-LAST:event_btExaminarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        llenarListCategorias();
        llenarListProveedor();      
    }//GEN-LAST:event_formWindowActivated

    private void btAddProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddProdActionPerformed

        if (VerificarCamposProd())
            {
             
            //foto
            String foto = txtRuta.getText();
            productoclase.setRuta_foto(foto);
        
            //descripcion
            String descrip = textDescrp.getText().toUpperCase();
            productoclase.setDetalle_producto(descrip);
        
            //cantidad bodega
            String cantidad = txtCantidad.getText();
            int cantid= Integer.parseInt(cantidad);
            productoclase.setCantidad_bodega(cantid);
        
            //costo unitario
            String costunitA = txtPUnitArr.getText();        
            int costUnA= Integer.parseInt(costunitA);
            productoclase.setCosto_unit_arr_producto(costUnA);
        
            //costo producto
            String costunitC = txtCostUnitC.getText();   
            int costunit= Integer.parseInt(costunitC);
            productoclase.setCosto_Producto(costunit);       
        
            //marca producto
            String marcProd = txtMarcaProd.getText().toUpperCase();
            productoclase.setMarca_producto(marcProd);
        
            //lista categoria
            String nomCategoria =listCategorias.getSelectedValue().toString();
            int idc = sqlproducto.getIdCategoria(nomCategoria);
            productoclase.setId_Categoria(idc);
            
            String nomProveedor =listProveedor.getSelectedValue().toString();
            int idp = sqlproducto.getIdProveedor(nomProveedor);
            proveedorclase.setId_proveedor(idp);
                    
            String existe = sqlproducto.existeProducto(marcProd, descrip , costUnA, costunit);
                if (existe.equals(""))
                    {
                   //sqlproducto.agregarProducto(productoclase, proveedorclase);
                   
                   if(sqlproducto.agregarProducto(productoclase,proveedorclase))
                   {
                   JOptionPane.showMessageDialog(rootPane, "Producto agregado correctamente",  "Notificación", JOptionPane.PLAIN_MESSAGE, iconoBueno);
                   this.dispose();
                   }
                 
                }
                else
                {
                JOptionPane.showMessageDialog(rootPane, "Atención, el Producto ya esta Registrado",  "Notificación", JOptionPane.PLAIN_MESSAGE, iconoError);
                }
                 
                
            }

        
        
    }//GEN-LAST:event_btAddProdActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    //llenarListCategorias();
    //llenarListProveedor();
        
    }//GEN-LAST:event_formWindowOpened

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c) == false) {
            evt.consume();
        }
        if(txtCantidad.getText().length()==8) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCantidadKeyTyped

    private void txtPUnitArrKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPUnitArrKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c) == false) {
            evt.consume();
        }
        if(txtPUnitArr.getText().length()==8) {
            evt.consume();
        }
    }//GEN-LAST:event_txtPUnitArrKeyTyped

    private void txtCostUnitCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCostUnitCKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c) == false) {
            evt.consume();
        }
        if(txtCostUnitC.getText().length()==8) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCostUnitCKeyTyped

    private void txtMarcaProdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMarcaProdKeyTyped
         String textoconvert = txtMarcaProd.getText();
         textoconvert.toUpperCase();
         
         if(txtMarcaProd.getText().length()== 40) {
            evt.consume();
        }
    }//GEN-LAST:event_txtMarcaProdKeyTyped

    private void txtMarcaProdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMarcaProdKeyPressed
        InputMap map2 =  txtMarcaProd.getInputMap( txtMarcaProd.WHEN_FOCUSED);
      map2.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null"); 
      
    }//GEN-LAST:event_txtMarcaProdKeyPressed

    private void btAddProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddProveedorActionPerformed
        dialogNuevoProveedorProd addProvP = new dialogNuevoProveedorProd(new javax.swing.JDialog(), true); //cambie la herencia de frame a jdialog
        addProvP.setVisible(true);
        addProvP.setResizable(false);
        addProvP.setLocationRelativeTo(null);
        addProvP.pack();

    }//GEN-LAST:event_btAddProveedorActionPerformed

    private void btAddCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddCategoriaActionPerformed
        dialogNuevaCategoriaProd addCategP = new dialogNuevaCategoriaProd(new javax.swing.JDialog(), true); //cambie la herencia de frame a jdialog
        addCategP.setVisible(true);
        addCategP.setResizable(false);
        addCategP.setLocationRelativeTo(null);
        addCategP.pack();
    }//GEN-LAST:event_btAddCategoriaActionPerformed

    private void txtMarcaProdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMarcaProdKeyReleased
        String valor = txtMarcaProd.getText();        
        if(valor.equals(""))        {
            txtMarcaProd.setBackground(new Color (255,255,204));
        }
        else        {
            txtMarcaProd.setBackground(new Color (255,255,255));
        }
    }//GEN-LAST:event_txtMarcaProdKeyReleased

    private void textDescrpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textDescrpKeyReleased
        String valor = textDescrp.getText();        
        if(valor.equals(""))        {
            textDescrp.setBackground(new Color (255,255,204));
        }
        else        {
            textDescrp.setBackground(new Color (255,255,255));
        }
    }//GEN-LAST:event_textDescrpKeyReleased

    private void txtPUnitArrKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPUnitArrKeyReleased
        String valor = txtPUnitArr.getText();        
        if(valor.equals(""))        {
            txtPUnitArr.setBackground(new Color (255,255,204));
        }
        else        {
            txtPUnitArr.setBackground(new Color (255,255,255));
        }
    }//GEN-LAST:event_txtPUnitArrKeyReleased

    private void txtCostUnitCKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCostUnitCKeyReleased
        String valor = txtCostUnitC.getText();        
        if(valor.equals(""))        {
            txtCostUnitC.setBackground(new Color (255,255,204));
        }
        else        {
            txtCostUnitC.setBackground(new Color (255,255,255));
        }
    }//GEN-LAST:event_txtCostUnitCKeyReleased

    private void txtCantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyReleased
        String valor = txtCantidad.getText();        
        if(valor.equals(""))        {
            txtCantidad.setBackground(new Color (255,255,204));
        }
        else        {
            txtCantidad.setBackground(new Color (255,255,255));
        }
    }//GEN-LAST:event_txtCantidadKeyReleased

    private void txtAddClDig1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddClDig1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddClDig1KeyTyped

    private void listProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listProveedorMouseClicked
                  
    }//GEN-LAST:event_listProveedorMouseClicked

    private void listProveedorValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listProveedorValueChanged
    
    }//GEN-LAST:event_listProveedorValueChanged

    private void listCategoriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listCategoriasMouseClicked
      
    }//GEN-LAST:event_listCategoriasMouseClicked

    private void btAddProd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddProd1ActionPerformed
int mensaje= JOptionPane.showConfirmDialog(rootPane, "Atención: Todos los cambios no Guardados se perderan\n¿Confirma Cancelar??", 
                        "\tCerrar", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,iconoAlerta);
                if(mensaje==JOptionPane.YES_NO_OPTION)
                {
                    this.dispose();
                }
    }//GEN-LAST:event_btAddProd1ActionPerformed

    private void textDescrpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textDescrpKeyTyped
if(textDescrp.getText().length()== 40) {
            evt.consume();
        }       
    }//GEN-LAST:event_textDescrpKeyTyped

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int mensaje= JOptionPane.showConfirmDialog(rootPane, "Atención: Todos los cambios no Guardados se perderan\n¿Confirma Cerrar esta ventana??", 
                        "\tCerrar", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
                if(mensaje==JOptionPane.YES_NO_OPTION)
                {
                    this.dispose();
                }
    }//GEN-LAST:event_formWindowClosing

    private void textDescrpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textDescrpKeyPressed
InputMap map2 =  textDescrp.getInputMap( textDescrp.WHEN_FOCUSED);
      map2.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");         // TODO add your handling code here:
    }//GEN-LAST:event_textDescrpKeyPressed

    private void txtCostUnitCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCostUnitCKeyPressed
InputMap map2 =  txtCostUnitC.getInputMap( txtCostUnitC.WHEN_FOCUSED);
      map2.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");         // TODO add your handling code here:
    }//GEN-LAST:event_txtCostUnitCKeyPressed

    private void txtPUnitArrKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPUnitArrKeyPressed
InputMap map2 =  txtPUnitArr.getInputMap( txtPUnitArr.WHEN_FOCUSED);
      map2.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");         // TODO add your handling code here:
    }//GEN-LAST:event_txtPUnitArrKeyPressed

    private void txtCantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyPressed
InputMap map2 =  txtCantidad.getInputMap( txtCantidad.WHEN_FOCUSED);
      map2.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");         // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadKeyPressed

public boolean VerificarCamposProd ()
{
    
    boolean respuesta=true;
    
    String variable1 = "";
    if(txtMarcaProd.getText().equals(""))
                {
                
                variable1=variable1+ "Debe ingresar una Marca \n";
                respuesta=false;
                txtMarcaProd.requestFocus();
                }
    else if(textDescrp.getText().equals(""))
                {
                
                variable1=variable1+ "Debe ingresar una Descripción \n";
                respuesta=false;
                textDescrp.requestFocus();
                }
     else if(txtCantidad.getText().equals(""))
                {
                
                variable1=variable1+ "Debe ingresar una Cantidad \n";
                respuesta=false;
                txtCantidad.requestFocus();
                }
      else if(txtPUnitArr.getText().equals(""))
                {
                
                variable1=variable1+ "Debe ingresar la cantidad de Precio Unitario \n";
                respuesta=false;
                txtPUnitArr.requestFocus();
                }
       else if(txtCostUnitC.getText().equals(""))
                {
                
                variable1=variable1+ "Debe ingresar un Costo Unitario \n";
                respuesta=false;
                txtCostUnitC.requestFocus();
                }
        else if(txtArchivo.getText().equals(""))
                {
                
                variable1=variable1+"Debe ingresar una imagen \n";
                respuesta=false;
                txtArchivo.requestFocus();
                }
        else if (listProveedor.getSelectedIndex()==-1)
        {
            variable1=variable1+"Debe Seleccionar un Proveedor \n";
            respuesta=false;
        }    
        else if (listCategorias.getSelectedIndex()==-1)
        {
            variable1=variable1+"Debe Seleccionar una Categoria \n";
            respuesta=false;
        }
        
       if(!respuesta)
    {
      JOptionPane.showMessageDialog(rootPane, variable1,  "Notificación", JOptionPane.PLAIN_MESSAGE, iconoAlerta);
        }
    
    return respuesta;
    
}
    
public void llenarListCategorias()
{
   
   sqlproducto.buscarCategorias();
   listCategorias.setModel(sqlproducto.listaCategorias);         
   
}
    
public void llenarListProveedor()
{
   
   sqlproducto.buscarProveedor();
   listProveedor.setModel(sqlproducto.listaProveedores);         
   
}

void limpiarcamposNuevoProd(){
txtRuta.setText("");
txtDirectorio.setText("");
txtArchivo.setText("");
txtMarcaProd.setText("");
textDescrp.setText("");
txtPUnitArr.setText("");
txtCostUnitC.setText("");
txtCantidad.setText("");
lbVistaPrevia.setText("");
        
}/*
public void llenarcbProveedor()
{
   productoclase.buscarPoveedores();
   cbProveedores.setModel(productoclase.comboProveedores);
            
}
    */


    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dialogNuevoProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dialogNuevoProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dialogNuevoProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dialogNuevoProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                dialogNuevoProducto dialog = new dialogNuevoProducto(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser BuscadorFoto;
    private javax.swing.JButton btAddCategoria;
    private javax.swing.JButton btAddProd;
    private javax.swing.JButton btAddProd1;
    private javax.swing.JButton btAddProveedor;
    private javax.swing.JButton btExaminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbVistaPrevia;
    private javax.swing.JList listCategorias;
    private javax.swing.JList listProveedor;
    private javax.swing.JTextArea textDescrp;
    private javax.swing.JTextField txtAddClDig1;
    private javax.swing.JTextField txtArchivo;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCostUnitC;
    private javax.swing.JTextField txtDirectorio;
    private javax.swing.JTextField txtMarcaProd;
    private javax.swing.JTextField txtPUnitArr;
    private javax.swing.JTextField txtRuta;
    // End of variables declaration//GEN-END:variables
DefaultTableModel llenadoCategorias = new DefaultTableModel();

}

