/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package arriendos;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Gabriel
 */
public class dialogBuscarIDArriendoFin extends javax.swing.JDialog {
Arriendo arriendoclase = new Arriendo();
SQLArriendo sqlarriendo = new SQLArriendo();

Icon iconoAlerta  =  new ImageIcon("C:/Sistema Muninn/Imagenes/alertaIcono.png");
Icon iconoBueno  =  new ImageIcon("C:/Sistema Muninn/Imagenes/aceptadoIcono.png");
Icon iconoError  =  new ImageIcon("C:/Sistema Muninn/Imagenes//errorIcono.png");
Icon iconoInfo  =  new ImageIcon("C:/Sistema Muninn/Imagenes/infoIcono.png"); 


    public dialogBuscarIDArriendoFin(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        
        sqlarriendo.tablaArriendosEnCurso.addColumn("ID Arriendo");
       // sqlarriendo.tablaArriendosEnCurso.addColumn("Cliente");
        //sqlarriendo.tablaArriendosEnCurso.addColumn("Usuario");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaIDArriendos = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        txtBuscadorIDArr = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbArrFinIDArr = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lbArrFinFechInicioArr = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbArrFinIDCliente = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbArrFinRutCliente = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbArrFinNombCliente = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lbUsuarioFinArr1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbUsuarioActual = new javax.swing.JLabel();
        btFinArriendoIngr = new javax.swing.JButton();
        btFinArriendoIngr1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MUNINN - Buscador ID Arriendo");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(null);

        jPanel5.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel5.setOpaque(false);

        jPanel6.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel6.setOpaque(false);

        jPanel2.setBackground(new java.awt.Color(38, 87, 163));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        tablaIDArriendos.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        tablaIDArriendos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaIDArriendos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaIDArriendos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaIDArriendosMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaIDArriendosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tablaIDArriendos);

        jLabel19.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(231, 227, 227));
        jLabel19.setText("Ingrese ID del Arriendo");

        txtBuscadorIDArr.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtBuscadorIDArr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscadorIDArrMouseClicked(evt);
            }
        });
        txtBuscadorIDArr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscadorIDArrKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscadorIDArrKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtBuscadorIDArr)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscadorIDArr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(38, 87, 163));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(231, 227, 227));
        jLabel4.setText("Informacion General");

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(231, 227, 227));
        jLabel13.setText("ID Arriendo");

        lbArrFinIDArr.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lbArrFinIDArr.setForeground(new java.awt.Color(231, 227, 227));
        lbArrFinIDArr.setText("No ha seleccionado ningun ID");

        jLabel15.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(231, 227, 227));
        jLabel15.setText("Fecha Emision");

        lbArrFinFechInicioArr.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lbArrFinFechInicioArr.setForeground(new java.awt.Color(231, 227, 227));
        lbArrFinFechInicioArr.setText("No ha seleccionado ningun ID");

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(231, 227, 227));
        jLabel1.setText("ID Cliente");

        lbArrFinIDCliente.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lbArrFinIDCliente.setForeground(new java.awt.Color(231, 227, 227));
        lbArrFinIDCliente.setText("No ha seleccionado ningun ID");

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(231, 227, 227));
        jLabel9.setText("Rut Cliente");

        lbArrFinRutCliente.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lbArrFinRutCliente.setForeground(new java.awt.Color(231, 227, 227));
        lbArrFinRutCliente.setText("No ha seleccionado ningun ID");

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(231, 227, 227));
        jLabel7.setText("Nombre del Cliente");

        lbArrFinNombCliente.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lbArrFinNombCliente.setForeground(new java.awt.Color(231, 227, 227));
        lbArrFinNombCliente.setText("No ha seleccionado ningun ID");

        jLabel16.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(231, 227, 227));
        jLabel16.setText("Usuario que realizo Arriendo");

        lbUsuarioFinArr1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lbUsuarioFinArr1.setForeground(new java.awt.Color(231, 227, 227));
        lbUsuarioFinArr1.setText("No ha seleccionado ningun ID");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(231, 227, 227));
        jLabel3.setText("Usuario Activo");

        lbUsuarioActual.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbUsuarioActual.setForeground(new java.awt.Color(231, 227, 227));
        lbUsuarioActual.setText("No ha seleccionado ningun ID");

        btFinArriendoIngr.setBackground(new java.awt.Color(65, 85, 128));
        btFinArriendoIngr.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btFinArriendoIngr.setForeground(new java.awt.Color(255, 255, 255));
        btFinArriendoIngr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoNuevo.png"))); // NOI18N
        btFinArriendoIngr.setText("Ingreso de Arriendo");
        btFinArriendoIngr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFinArriendoIngrActionPerformed(evt);
            }
        });

        btFinArriendoIngr1.setBackground(new java.awt.Color(65, 85, 128));
        btFinArriendoIngr1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btFinArriendoIngr1.setForeground(new java.awt.Color(255, 255, 255));
        btFinArriendoIngr1.setText("Cerrar Ventana");
        btFinArriendoIngr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFinArriendoIngr1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btFinArriendoIngr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 4, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel13))
                                .addGap(99, 99, 99)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbArrFinIDCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbArrFinRutCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbArrFinFechInicioArr, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbArrFinIDArr)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbUsuarioFinArr1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbArrFinNombCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbUsuarioActual, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(20, 20, 20))
                    .addComponent(btFinArriendoIngr1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lbArrFinIDArr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(lbArrFinFechInicioArr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbArrFinIDCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lbArrFinRutCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lbArrFinNombCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(lbUsuarioFinArr1))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbUsuarioActual))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btFinArriendoIngr, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btFinArriendoIngr1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel4.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(231, 227, 227));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/miniSeguimiento.png"))); // NOI18N
        jLabel2.setText("Buscador de Arriendos Activos");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(jPanel5);
        jPanel5.setBounds(11, 12, 718, 510);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoArriendos3.png"))); // NOI18N
        jPanel3.add(jLabel5);
        jLabel5.setBounds(0, 0, 790, 560);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaIDArriendosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaIDArriendosMouseClicked
       

    }//GEN-LAST:event_tablaIDArriendosMouseClicked

    private void txtBuscadorIDArrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscadorIDArrMouseClicked
        txtBuscadorIDArr.setText("");
    }//GEN-LAST:event_txtBuscadorIDArrMouseClicked

    private void txtBuscadorIDArrKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscadorIDArrKeyReleased
        String buscador = txtBuscadorIDArr.getText();
        sqlarriendo.buscaArriendosEnCursoIDLike(buscador);
        tablaIDArriendos.setModel(sqlarriendo.tablaArriendosEnCurso);
    }//GEN-LAST:event_txtBuscadorIDArrKeyReleased

    private void txtBuscadorIDArrKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscadorIDArrKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c) == false) {
            evt.consume();
        }
    }//GEN-LAST:event_txtBuscadorIDArrKeyTyped

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        sqlarriendo.buscaArriendosEnCursoID(); 
        tablaIDArriendos.setModel(sqlarriendo.tablaArriendosEnCurso);
    }//GEN-LAST:event_formWindowOpened

    private void btFinArriendoIngrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFinArriendoIngrActionPerformed
int rows = tablaIDArriendos.getRowCount();
        
        if(rows > 0)
        {
            if(tablaIDArriendos.getSelectedRows().length > 0)
            {
                int mensaje= JOptionPane.showConfirmDialog(rootPane, "¿Confirma agregar el Arriendo N° "+lbArrFinIDArr.getText()+"?",
                "\tConfirmación", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,iconoAlerta);
                if(mensaje==JOptionPane.YES_NO_OPTION)
                {
                    this.dispose();
                    dialogFinArriendo idarriendofin = new dialogFinArriendo(new javax.swing.JDialog(), true); //cambie la herencia de frame a jdialog
     //   System.out.print("Abriendo Modificar Información del Cliente "+lb_cod.getText());
                    
                    idarriendofin.lbUsuarioFinArr.setText(lbUsuarioActual.getText());
        
                    idarriendofin.lbArrFinIDArr.setText(lbArrFinIDArr.getText());
                    idarriendofin.lbArrFinFechInicioArr.setText(lbArrFinFechInicioArr.getText());
                    idarriendofin.lbArrFinIDCliente.setText(lbArrFinIDCliente.getText());
                    idarriendofin.lbArrFinNombCliente.setText(lbArrFinNombCliente.getText());
                    idarriendofin.lbArrFinRutCliente.setText(lbArrFinRutCliente.getText());
                    //idarriendofin.lbUsuarioFinArr.setText(lbUsuarioFinArr1.getText());
        
                    idarriendofin.setVisible(true);
                    idarriendofin.setResizable(false);
                    idarriendofin.setLocationRelativeTo(null);
                    idarriendofin.pack(); 
                }  
                else
                {
                
                }
            }
            else
            {
            JOptionPane.showMessageDialog(rootPane, "No ah seleccionado ningun Cliente","Notificación", JOptionPane.PLAIN_MESSAGE, iconoAlerta);
            lbArrFinIDArr.setText("");
                lbArrFinFechInicioArr.setText("");
                lbArrFinIDCliente.setText("");
                lbArrFinNombCliente.setText("");
                lbArrFinRutCliente.setText("");
                lbUsuarioFinArr1.setText("");
            }
        }
        else
        {
         JOptionPane.showMessageDialog(rootPane, "No hay Clientes Registrados en la tabla","Notificación", JOptionPane.PLAIN_MESSAGE, iconoInfo);
        }
    }//GEN-LAST:event_btFinArriendoIngrActionPerformed

    private void btFinArriendoIngr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFinArriendoIngr1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btFinArriendoIngr1ActionPerformed

    private void tablaIDArriendosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaIDArriendosMousePressed
        // TODO add your handling code here:
         btFinArriendoIngr.setEnabled(true);
        
        int row = tablaIDArriendos.getSelectedRow();
        String id = tablaIDArriendos.getValueAt(row, 0).toString();

        // c

        ArrayList datos = new ArrayList();
        datos = sqlarriendo.buscarArriendoSelecc(id);

        lbArrFinIDArr.setText(datos.get(0).toString());
        lbArrFinFechInicioArr.setText(datos.get(1).toString());
        lbArrFinIDCliente.setText(datos.get(2).toString());
        lbArrFinRutCliente.setText(datos.get(3).toString() + "-" + datos.get(4).toString());
        lbArrFinNombCliente.setText(datos.get(5).toString() + " " + datos.get(6).toString());
        lbUsuarioFinArr1.setText(datos.get(7).toString());
    }//GEN-LAST:event_tablaIDArriendosMousePressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        tablaIDArriendos.getTableHeader().setReorderingAllowed(false) ;
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dialogBuscarIDArriendoFin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dialogBuscarIDArriendoFin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dialogBuscarIDArriendoFin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dialogBuscarIDArriendoFin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                dialogBuscarIDArriendoFin dialog = new dialogBuscarIDArriendoFin(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFinArriendoIngr;
    private javax.swing.JButton btFinArriendoIngr1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbArrFinFechInicioArr;
    private javax.swing.JLabel lbArrFinIDArr;
    private javax.swing.JLabel lbArrFinIDCliente;
    private javax.swing.JLabel lbArrFinNombCliente;
    private javax.swing.JLabel lbArrFinRutCliente;
    public static javax.swing.JLabel lbUsuarioActual;
    private javax.swing.JLabel lbUsuarioFinArr1;
    private javax.swing.JTable tablaIDArriendos;
    private javax.swing.JTextField txtBuscadorIDArr;
    // End of variables declaration//GEN-END:variables
}
