/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package arriendos;

import clientes.Cliente;
import com.mysql.jdbc.PreparedStatement;
import conexion.ConexionBD;
import inicio.inicioRapido;
import java.awt.Event;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.*;

/**
 *
 * @author GabrielNote
 */
public class dialogFinArriendo extends javax.swing.JDialog {
SQLArriendo sqlarriendo = new SQLArriendo();
Arriendo arriendoclase = new Arriendo();

Icon iconoAlerta  =  new ImageIcon("C:/Sistema Muninn/Imagenes/alertaIcono.png");
Icon iconoBueno  =  new ImageIcon("C:/Sistema Muninn/Imagenes/aceptadoIcono.png");
Icon iconoError  =  new ImageIcon("C:/Sistema Muninn/Imagenes//errorIcono.png");
Icon iconoInfo  =  new ImageIcon("C:/Sistema Muninn/Imagenes/infoIcono.png"); 



ConexionBD conexionbd = new ConexionBD();
Cliente clienteclase = new Cliente();
    
    public dialogFinArriendo(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaProductosFinArr = new javax.swing.JTable();
        btIngresoProdFin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtGarantiaExtra = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTotalSoloArrendo = new javax.swing.JTextField();
        txtTotalTotal = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbArrFinNombCliente = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbArrFinIDCliente = new javax.swing.JLabel();
        lbArrFinRutCliente = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lbUsuarioFinArr = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        btCalculoHoras = new javax.swing.JButton();
        cbHoraArriendoFin = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jdchFechaFin = new com.toedter.calendar.JDateChooser();
        jLabel15 = new javax.swing.JLabel();
        lbArrFinFechInicioArr = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbArrFinIDArr = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtHorasTotalesArr = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btIngresoFinArriendo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MUNINN - Termino de un Arriendo");
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(1100, 485));
        setMinimumSize(new java.awt.Dimension(1100, 485));
        setPreferredSize(new java.awt.Dimension(1100, 485));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel8.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel8.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(193, 205, 231));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setOpaque(false);

        jPanel4.setBackground(new java.awt.Color(38, 87, 163));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(19, 60, 124)));

        tablaProductosFinArr.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        tablaProductosFinArr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Producto", "Nombre Prod.", "Cantidad Final", "Total Arriendo Producto", "Total Garantia Producto", "Total  Arriendo Producto"
            }
        ));
        jScrollPane2.setViewportView(tablaProductosFinArr);

        btIngresoProdFin.setBackground(new java.awt.Color(65, 85, 128));
        btIngresoProdFin.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btIngresoProdFin.setForeground(new java.awt.Color(235, 233, 233));
        btIngresoProdFin.setText("Revision Producto por Producto");
        btIngresoProdFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIngresoProdFinActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ingreso de Productos Arrendados");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Valor Por concepto de garantia:");

        txtGarantiaExtra.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtGarantiaExtra.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Total Arriendo");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Total a Cancelar");

        txtTotalSoloArrendo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtTotalSoloArrendo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtTotalSoloArrendo.setEnabled(false);

        txtTotalTotal.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtTotalTotal.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtTotalTotal.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(btIngresoProdFin, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtGarantiaExtra, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtTotalSoloArrendo))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txtTotalTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btIngresoProdFin)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtTotalSoloArrendo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtGarantiaExtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTotalTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(38, 87, 163));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(19, 60, 124)));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID Cliente");

        lbArrFinNombCliente.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbArrFinNombCliente.setForeground(new java.awt.Color(255, 255, 255));
        lbArrFinNombCliente.setText("Nombre del Cliente");
        lbArrFinNombCliente.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Rut Cliente");

        lbArrFinIDCliente.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbArrFinIDCliente.setForeground(new java.awt.Color(255, 255, 255));
        lbArrFinIDCliente.setText("ID Cliente");
        lbArrFinIDCliente.setBorder(new javax.swing.border.MatteBorder(null));

        lbArrFinRutCliente.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbArrFinRutCliente.setForeground(new java.awt.Color(255, 255, 255));
        lbArrFinRutCliente.setText("Rut Cliente");
        lbArrFinRutCliente.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Nombre del Cliente");

        jPanel6.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel6.setOpaque(false);

        lbUsuarioFinArr.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lbUsuarioFinArr.setForeground(new java.awt.Color(204, 204, 204));
        lbUsuarioFinArr.setText("Valor");
        lbUsuarioFinArr.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel16.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("Usuario Activo");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(lbUsuarioFinArr, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(lbUsuarioFinArr))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbArrFinRutCliente)
                            .addComponent(lbArrFinIDCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 199, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(lbArrFinNombCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lbArrFinIDCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(lbArrFinRutCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(lbArrFinNombCliente))))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jButton3.setBackground(new java.awt.Color(65, 85, 128));
        jButton3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(235, 233, 233));
        jButton3.setText("Cancelar Operación");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel10.setBackground(new java.awt.Color(38, 87, 163));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(19, 60, 124)));

        jPanel7.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel7.setOpaque(false);

        btCalculoHoras.setBackground(new java.awt.Color(65, 85, 128));
        btCalculoHoras.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btCalculoHoras.setForeground(new java.awt.Color(235, 233, 233));
        btCalculoHoras.setText("Calcular Horas");
        btCalculoHoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalculoHorasActionPerformed(evt);
            }
        });

        cbHoraArriendoFin.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        cbHoraArriendoFin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una Hora", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00" }));

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Hora Termino");

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Fecha Termino Arriendo");

        jdchFechaFin.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jdchFechaFin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jdchFechaFinKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jdchFechaFinKeyReleased(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Fecha Emision");

        lbArrFinFechInicioArr.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lbArrFinFechInicioArr.setForeground(new java.awt.Color(255, 255, 255));
        lbArrFinFechInicioArr.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("ID Arriendo");

        lbArrFinIDArr.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lbArrFinIDArr.setForeground(new java.awt.Color(255, 255, 255));
        lbArrFinIDArr.setText("1");
        lbArrFinIDArr.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btCalculoHoras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbHoraArriendoFin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jdchFechaFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(lbArrFinIDArr, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbArrFinFechInicioArr, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lbArrFinIDArr))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(lbArrFinFechInicioArr, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jdchFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbHoraArriendoFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addComponent(btCalculoHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(38, 87, 163)));
        jPanel2.setOpaque(false);

        jLabel12.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Total Horas Arriendo");

        txtHorasTotalesArr.setBackground(new java.awt.Color(38, 87, 163));
        txtHorasTotalesArr.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtHorasTotalesArr.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtHorasTotalesArr.setEnabled(false);
        txtHorasTotalesArr.setOpaque(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(txtHorasTotalesArr, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtHorasTotalesArr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoTerminarArriendo.png"))); // NOI18N
        jLabel8.setText("Finalizar un Arriendo");

        btIngresoFinArriendo.setBackground(new java.awt.Color(65, 85, 128));
        btIngresoFinArriendo.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btIngresoFinArriendo.setForeground(new java.awt.Color(235, 233, 233));
        btIngresoFinArriendo.setText("Finalizar Arriendo");
        btIngresoFinArriendo.setEnabled(false);
        btIngresoFinArriendo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIngresoFinArriendoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btIngresoFinArriendo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btIngresoFinArriendo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel8.add(jPanel1);
        jPanel1.setBounds(11, 12, 1070, 500);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoArriendos3.png"))); // NOI18N
        jPanel8.add(jLabel4);
        jLabel4.setBounds(0, 0, 1150, 540);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 1092, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btIngresoProdFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIngresoProdFinActionPerformed
    int rows = tablaProductosFinArr.getRowCount();
        
    if(rows > 0)
    {
    int mensaje= JOptionPane.showConfirmDialog(rootPane, "Los Productos ya fueron verificados \n ¿Confirma verificar otra vez los productos?", "\tConfirmación",
    JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,iconoAlerta);

     if(mensaje==JOptionPane.YES_NO_OPTION)
            { 
                dialogVerProdArr verprodverfi = new dialogVerProdArr(new javax.swing.JDialog(), true);
                try {
                    int filas=tablaProductosFinArr.getRowCount();
                    for (int i = 0;filas>i; i++) {
                    verprodverfi.tablaProductoFinArr.removeRow(0);
                    
                    }
                    VerificarProductos();
                    } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, "Error al limpiar la tabla.",  "Notificación", JOptionPane.PLAIN_MESSAGE, iconoError);
                    }
            }
        
    }
    else
    {
       VerificarProductos(); 
    }
        
    }//GEN-LAST:event_btIngresoProdFinActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       
        tablaProductosFinArr.getTableHeader().setReorderingAllowed(false) ;
        
        if(txtHorasTotalesArr.getText().equals("")){
            btIngresoProdFin.setEnabled(false);
        }else { 
            btIngresoProdFin.setEnabled(true);
        }
        
        int totalRow= tablaProductosFinArr.getRowCount();
        

        double sumatoriaGarantia;        
        int sumatoriaGarantia1=0;
        
        double sumatoriaArriendo;        
        int sumatoriaArriendo1=0;
        
        
        totalRow-=1; 
        for(int i=0;i<=(totalRow);i++){
        sumatoriaGarantia= Double.parseDouble(String.valueOf(tablaProductosFinArr.getValueAt(i,4)));
        sumatoriaGarantia1+=sumatoriaGarantia;
        
        sumatoriaArriendo= Double.parseDouble(String.valueOf(tablaProductosFinArr.getValueAt(i,5)));
        sumatoriaArriendo1+=sumatoriaArriendo;
        } 
        
        txtGarantiaExtra.setText(String.valueOf(sumatoriaGarantia1));
        txtTotalSoloArrendo.setText(String.valueOf(sumatoriaArriendo1));
        
        
        int GarantiTotal = Integer.parseInt(txtGarantiaExtra.getText());
        int ArriendosTotal = Integer.parseInt(txtTotalSoloArrendo.getText());
        int totalTotal = GarantiTotal+ArriendosTotal;
        
        String numCadena= String.valueOf(totalTotal);
        
        txtTotalTotal.setText(numCadena);
        
        if(txtTotalTotal.getText().equals("0"))
        {
        btIngresoFinArriendo.setEnabled(false);
        }
        else
        {
        btIngresoFinArriendo.setEnabled(true);
        }
    }//GEN-LAST:event_formWindowActivated

    private void btCalculoHorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalculoHorasActionPerformed
        if(verificarParaCalculoHrs())
        {
        btIngresoProdFin.setEnabled(true);
        String idarr = lbArrFinIDArr.getText();
        
        int añoarr = jdchFechaFin.getCalendar().get(Calendar.YEAR);
        String añoarrStr= String.valueOf(añoarr);        
        int mesarr = jdchFechaFin.getCalendar().get(Calendar.MONTH)+1;
        String mesarrStr= String.valueOf(mesarr);        
        int diaarr = jdchFechaFin.getCalendar().get(Calendar.DATE);
        String diaarrStr= String.valueOf(diaarr);        
        Object horaarr = cbHoraArriendoFin.getSelectedItem();
        String horaarriendo = String.valueOf(horaarr);        
        String horaarrcompl = añoarrStr+"-"+mesarrStr+"-"+diaarrStr+" "+horaarriendo+":00";
        
        String horasTot = sqlarriendo.obtenercantidadHoras(horaarrcompl, idarr);
        int horasTotalesObt = Integer.parseInt(horasTot);
        
        if(horasTotalesObt>=1)
        {
        txtHorasTotalesArr.setText(horasTot);
        }
        else
        {
        JOptionPane.showMessageDialog(rootPane, "Atención, La Hora o Fecha son incorrectas",  "Notificación", JOptionPane.PLAIN_MESSAGE, iconoError);
        txtHorasTotalesArr.setText("");
        }
        }
    }//GEN-LAST:event_btCalculoHorasActionPerformed

    private void jdchFechaFinKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jdchFechaFinKeyReleased
        
    }//GEN-LAST:event_jdchFechaFinKeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int mensaje= JOptionPane.showConfirmDialog(rootPane, "Se perderan los cambios no guardados "
                + "\n¿Confirma cancelar esta operación?", 
                        "\tConfirmacion", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,iconoAlerta);
                if(mensaje==JOptionPane.YES_NO_OPTION)
                {
                    this.dispose();
                }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int mensaje= JOptionPane.showConfirmDialog(rootPane, "Se perderan los cambios no guardados "
                + "\n¿Confirma cancelar esta operación?", 
                        "\tConfirmacion", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,iconoAlerta);
                if(mensaje==JOptionPane.YES_NO_OPTION)
                {
                    this.dispose();
                }
    }//GEN-LAST:event_formWindowClosing

    private void btIngresoFinArriendoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIngresoFinArriendoActionPerformed
if(VerificarCamposArriendoFin()) 
{
        int añoarr = jdchFechaFin.getCalendar().get(Calendar.YEAR);
        String añoarrStr= String.valueOf(añoarr);        
        int mesarr = jdchFechaFin.getCalendar().get(Calendar.MONTH)+1;
        String mesarrStr= String.valueOf(mesarr);        
        int diaarr = jdchFechaFin.getCalendar().get(Calendar.DATE);
        String diaarrStr= String.valueOf(diaarr);         
        Object horaarr = cbHoraArriendoFin.getSelectedItem();
        String horaarriendo = String.valueOf(horaarr);
        String horaarrcompl = añoarrStr+"-"+mesarrStr+"-"+diaarrStr+" "+horaarriendo+":00";
        arriendoclase.setFecha_inicio_arriendo(horaarrcompl);         
        arriendoclase.setFecha_fin_arriendo(horaarrcompl);         
        
        String fechfin =txtHorasTotalesArr.getText();
        arriendoclase.setHoras_totales_arriendo(fechfin);        
        String totalarriendoxprod = txtTotalSoloArrendo.getText();
        arriendoclase.setArriendo_total_productos_fin(totalarriendoxprod);        
        String txtGarantiaExra = txtGarantiaExtra.getText();
        arriendoclase.setGarantia_total_productos_fin(txtGarantiaExra);                
        String totalTotal = txtTotalTotal.getText();
        arriendoclase.setTotal_total_arriendo(totalTotal);                
        String usuario = lbUsuarioFinArr.getText();
        arriendoclase.setCuenta_usuario_arriendo_fin(usuario);     
        
        String idArriendo = lbArrFinIDArr.getText();
        
        sqlarriendo.ingresoArriendoFinalizacion(clienteclase, arriendoclase, idArriendo);
        
        
        ingresarproductosTablaFin(idArriendo);
        actualizarCantidadProdFin(idArriendo);
}
        
        
        
        
        
    }//GEN-LAST:event_btIngresoFinArriendoActionPerformed

    private void jdchFechaFinKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jdchFechaFinKeyPressed
InputMap map2 =  jdchFechaFin.getInputMap( jdchFechaFin.WHEN_FOCUSED);
      map2.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");         // TODO add your handling code here:
    }//GEN-LAST:event_jdchFechaFinKeyPressed

public boolean verificarParaCalculoHrs()
{
    boolean respuesta=true;
    
    String variable1 = "";
     if(jdchFechaFin.getDate() == null)
                {                
                variable1=variable1+ "Ingrese una Fecha \n";
                respuesta=false;
                jdchFechaFin.requestFocus();
                }
    else if(cbHoraArriendoFin.getSelectedItem().equals("Seleccione una Hora"))
                {
                variable1=variable1+ "Seleccione una Hora \n";
                respuesta=false;
                cbHoraArriendoFin.requestFocus();
                }    
       if(!respuesta)
    {
        JOptionPane.showMessageDialog(rootPane, variable1,  "Notificación", JOptionPane.PLAIN_MESSAGE, iconoAlerta);
        }
    
    return respuesta;    
}
public void VerificarProductos()
{
String idarr = lbArrFinIDArr.getText();
            String cantidadproducto = sqlarriendo.obtenercantidadProdArrendados(idarr);
            int cantidad = Integer.parseInt(cantidadproducto);
        
            PreparedStatement ps1 = null;
            ResultSet resultado = null;
            conexionbd.conectar();
        
            for(int i =0; i<cantidad;i++)
            { 
                    String sql1 = "SELECT id_Producto, Marca, DetalleProd, CostUnitArr,CostoProducto, CantidadInicioArrP "
                    + "FROM detalle_arriendo, arriendo, producto "
                    + "WHERE id_arriendo="+idarr+" "
                    + "AND arriendo.idarriendo=detalle_arriendo.id_arriendo "
                    + "AND producto.idproducto=detalle_arriendo.id_producto limit "+i+",1";
                 try {
                    ps1 = (PreparedStatement) conexionbd.getconexion().prepareStatement(sql1);
                    resultado= ps1.executeQuery(sql1);
                    System.out.print("Consulta: "+ sql1+"\n");
                    while (resultado.next())
                    {
                    String idArr=resultado.getString("id_Producto");
                    String marc=resultado.getString("Marca");
                    String detall=resultado.getString("DetalleProd");
                    int costunit=resultado.getInt("CostUnitArr");
                    int costprod=resultado.getInt("CostoProducto");
                    int cantid=resultado.getInt("CantidadInicioArrP");
                    
                    String costounithrArr = String.valueOf(costunit);
                    String costounithrCom = String.valueOf(costprod);
                    String cantidadEntreg = String.valueOf(cantid);
                    
                    dialogVerProdArr verprodverfi = new dialogVerProdArr(new javax.swing.JDialog(), true);
                      
                    verprodverfi.lbCodProdSelec.setText(idArr);
                    verprodverfi.txtaProductoDescrp.setText(marc+" "+detall);
                    verprodverfi.lbHorasArr.setText(txtHorasTotalesArr.getText());
                    verprodverfi.lbValorArr.setText(costounithrArr);
                    verprodverfi.lbValorGarant.setText(costounithrCom);
                    verprodverfi.lbCantidadEntregada.setText(cantidadEntreg);
            
                    verprodverfi.setResizable(false);
                    verprodverfi.setVisible(true);
                    verprodverfi.setLocationRelativeTo(null);
                    verprodverfi.pack();
                    }
                 }
                catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, "Error SQL: "+ ex.getMessage(),"Notificación", JOptionPane.PLAIN_MESSAGE, iconoError);
                }
            }


}

public boolean VerificarCamposArriendoFin()
{
    boolean respuesta=true;
    
    String variable1 = "";
     if(jdchFechaFin.getDate() == null)
                {                
                variable1=variable1+ "Ingrese una Fecha \n";
                respuesta=false;
                jdchFechaFin.requestFocus();
                }
    else if(cbHoraArriendoFin.getSelectedItem().equals("Seleccione una Hora"))
                {
                variable1=variable1+ "Seleccione una Hora \n";
                respuesta=false;
                cbHoraArriendoFin.requestFocus();
                }
     else if(txtTotalTotal.getText().equals("0"))
                {
                variable1=variable1+ "No ha verificado Cantidades de los productos\n"
                        + "Valla al boton 'Revisar'";
                respuesta=false;
                txtTotalTotal.requestFocus();
                }
    
       if(!respuesta)
    {
      JOptionPane.showMessageDialog(rootPane, variable1,  "Notificación", JOptionPane.PLAIN_MESSAGE, iconoAlerta);
        }
    
    return respuesta;    
}


public void ingresarproductosTablaFin(String idArrUltim)
{
conexionbd.conectar();
for (int ii = 0; ii < tablaProductosFinArr.getRowCount(); ii++) 
         {
    PreparedStatement ps = null; 
    String SQL1 = " UPDATE  detalle_arriendo SET "
            + "CantidadFinArrP = '"+tablaProductosFinArr.getValueAt(ii, 2)+"' , "
            + "TotalArriendoP = '"+tablaProductosFinArr.getValueAt(ii, 3)+"' , "
            + "GarantiaProductoTotal = '"+tablaProductosFinArr.getValueAt(ii, 4)+"' , "
            + "TotalFinalArrP = '"+tablaProductosFinArr.getValueAt(ii, 5)+"' "
            + "WHERE  id_Arriendo ="+idArrUltim+" "
            + "AND id_Producto ='"+tablaProductosFinArr.getValueAt(ii, 0)+"'";

    try {
        ps = (PreparedStatement) conexionbd.getconexion().prepareStatement(SQL1);
        ps.executeUpdate();
        
        System.out.print("Ejecutando consulta Fin Arriendo Parte 2: "+SQL1+"\n");
        
        }catch (SQLException e){
            JOptionPane.showMessageDialog(rootPane,"132446 "+e.getMessage(),"Notificación", JOptionPane.PLAIN_MESSAGE, iconoError);
            e.printStackTrace();
        }catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,"133426 "+e.getMessage() ,"Notificación", JOptionPane.PLAIN_MESSAGE, iconoError);
            e.printStackTrace();
            }
         }

}

public void actualizarCantidadProdFin(String idArriendo)
{
conexionbd.conectar();
for (int ii = 0; ii < tablaProductosFinArr.getRowCount(); ii++) 
         {
           String valor1=tablaProductosFinArr.getValueAt(ii, 0).toString(); //id del producto
           
           int cantidadActualprod = sqlarriendo.obtenerCantidadActual(valor1); //cantidad actual bodega 
            System.out.print("Obteniendo valor actual bodega: "+cantidadActualprod+"\n\n");
           
           String cantidadActualizar=tablaProductosFinArr.getValueAt(ii, 2).toString();//cantidad para actualizar
           
           int cantidadprod = Integer.parseInt(cantidadActualizar);           
           int sumaProd= cantidadActualprod+cantidadprod;
           
           System.out.print("Suma Cantidad Bodega: "+cantidadActualprod+" y cantida Para Actualizar: "+cantidadActualizar+" Total:"+sumaProd+"\n");
           
           PreparedStatement ps = null; 
            String SQL1 = ""
                    + "UPDATE producto SET CantidadBodega =  '"+sumaProd+"' WHERE idproducto ='"+valor1+"';";
            
    System.out.print("Consulta SQL: "+SQL1+"\n");
    
    try {
        ps = (PreparedStatement) conexionbd.getconexion().prepareStatement(SQL1);
        ps.executeUpdate();
        System.out.print("Ejecutando consulta...\n");
        
        
        this.dispose();
        }catch (SQLException e){
            JOptionPane.showMessageDialog(rootPane,"13A26 "+e.getMessage(),"Notificación", JOptionPane.PLAIN_MESSAGE, iconoError);
            e.printStackTrace();
        }catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,"13E26 "+e.getMessage(),"Notificación", JOptionPane.PLAIN_MESSAGE, iconoError);
            e.printStackTrace();
            }
         }
    JOptionPane.showMessageDialog(rootPane, "Arriendo N°"+idArriendo+" Finalizado con exito \n Se generara un Informe","Notificación", JOptionPane.PLAIN_MESSAGE, iconoBueno);
        
    String nombrereporte = "ReporteArriendoFin";
    ReportesArriendo reporte = new ReportesArriendo();
    String parametroid = "IdArriendo";
    
        reporte.runReporte(idArriendo, nombrereporte, parametroid);
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dialogFinArriendo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dialogFinArriendo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dialogFinArriendo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dialogFinArriendo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                dialogFinArriendo dialog = new dialogFinArriendo(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCalculoHoras;
    private javax.swing.JButton btIngresoFinArriendo;
    private javax.swing.JButton btIngresoProdFin;
    private javax.swing.JComboBox cbHoraArriendoFin;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser jdchFechaFin;
    public static javax.swing.JLabel lbArrFinFechInicioArr;
    public static javax.swing.JLabel lbArrFinIDArr;
    public static javax.swing.JLabel lbArrFinIDCliente;
    public static javax.swing.JLabel lbArrFinNombCliente;
    public static javax.swing.JLabel lbArrFinRutCliente;
    public static javax.swing.JLabel lbUsuarioFinArr;
    public static javax.swing.JTable tablaProductosFinArr;
    private javax.swing.JTextField txtGarantiaExtra;
    private javax.swing.JTextField txtHorasTotalesArr;
    private javax.swing.JTextField txtTotalSoloArrendo;
    private javax.swing.JTextField txtTotalTotal;
    // End of variables declaration//GEN-END:variables
}
