/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package arriendos;

import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author GabrielNote
 */
public class dialogArriendosCompletados extends javax.swing.JDialog {
SQLArriendo sqlarriendo = new SQLArriendo();
Icon iconoAlerta  =  new ImageIcon("C:/Sistema Muninn/Imagenes/alertaIcono.png");
Icon iconoBueno  =  new ImageIcon("C:/Sistema Muninn/Imagenes/aceptadoIcono.png");
Icon iconoError  =  new ImageIcon("C:/Sistema Muninn/Imagenes//errorIcono.png");
Icon iconoInfo  =  new ImageIcon("C:/Sistema Muninn/Imagenes/infoIcono.png"); 

    public dialogArriendosCompletados(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        
        
        sqlarriendo.tablaArriendosTerminados.addColumn("id Arriendo");
        sqlarriendo.tablaArriendosTerminados.addColumn("Fecha Finalización");
        sqlarriendo.tablaArriendosTerminados.addColumn("Total Horas");
        sqlarriendo.tablaArriendosTerminados.addColumn("Total Arriendo");
        sqlarriendo.tablaArriendosTerminados.addColumn("Cliente");
        sqlarriendo.tablaArriendosTerminados.addColumn("Usuario");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtBuscadorArrTerminados = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaArriendosListos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btDetalleArrComplet = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MUNINN - Visualizador Arriendos Terminados");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(219, 228, 235));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setOpaque(false);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Buscador por ID del arriendo y  Nombre del Cliente");

        txtBuscadorArrTerminados.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtBuscadorArrTerminados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscadorArrTerminadosKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscadorArrTerminados, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtBuscadorArrTerminados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(40, 70, 820, 50);

        tablaArriendosListos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaArriendosListos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaArriendosListos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaArriendosListosMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaArriendosListosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tablaArriendosListos);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(39, 125, 820, 260);

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/miniArriendosTerminados.png"))); // NOI18N
        jLabel1.setText("Registro de Arriendos Completados");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(290, 20, 396, 45);

        btDetalleArrComplet.setBackground(new java.awt.Color(65, 85, 128));
        btDetalleArrComplet.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        btDetalleArrComplet.setForeground(new java.awt.Color(255, 255, 255));
        btDetalleArrComplet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/miniSeguimiento.png"))); // NOI18N
        btDetalleArrComplet.setText("Detalle del Arriendo Seleccionado");
        btDetalleArrComplet.setEnabled(false);
        btDetalleArrComplet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDetalleArrCompletActionPerformed(evt);
            }
        });
        jPanel1.add(btDetalleArrComplet);
        btDetalleArrComplet.setBounds(41, 403, 820, 57);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoArriendos.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(1, 1, 960, 480);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        sqlarriendo.buscaArriendosTerminados(); 
        tablaArriendosListos.setModel(sqlarriendo.tablaArriendosTerminados);
    }//GEN-LAST:event_formWindowOpened

    private void tablaArriendosListosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaArriendosListosMouseClicked
        
        
    }//GEN-LAST:event_tablaArriendosListosMouseClicked

    private void btDetalleArrCompletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDetalleArrCompletActionPerformed
int rows = tablaArriendosListos.getRowCount();
        
        if(rows > 0)
        {
            if(tablaArriendosListos.getSelectedRows().length > 0)
            {
        
        this.dispose();
        int row = tablaArriendosListos.getSelectedRow();         
        String id=tablaArriendosListos.getValueAt(row, 0).toString();
        
        dialogInfoArriendoFin inforarrtermin = new dialogInfoArriendoFin(new javax.swing.JDialog(), true);
        
        inforarrtermin.lbCodArriendo.setText(id);
                
        inforarrtermin.setResizable(false);
        inforarrtermin.setVisible(true);
        inforarrtermin.setLocationRelativeTo(null);
        }
            else
            {
            JOptionPane.showMessageDialog(rootPane, "No ah seleccionado ningun Arriendo","Notificación", JOptionPane.PLAIN_MESSAGE, iconoAlerta);
            }
        }
        else
        {
         JOptionPane.showMessageDialog(rootPane, "No hay arriendos en la tabla","Notificación", JOptionPane.PLAIN_MESSAGE, iconoAlerta);
        }
    }//GEN-LAST:event_btDetalleArrCompletActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        tablaArriendosListos.getTableHeader().setReorderingAllowed(false) ;
        
        sqlarriendo.buscaArriendosTerminados(); 
        tablaArriendosListos.setModel(sqlarriendo.tablaArriendosTerminados);
        
        
        
        
    }//GEN-LAST:event_formWindowActivated

    private void txtBuscadorArrTerminadosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscadorArrTerminadosKeyReleased
       String buscador = txtBuscadorArrTerminados.getText();
        sqlarriendo.buscarArriendoTerminLike(buscador);
        tablaArriendosListos.setModel(sqlarriendo.tablaArriendosTerminados);
    }//GEN-LAST:event_txtBuscadorArrTerminadosKeyReleased

    private void tablaArriendosListosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaArriendosListosMousePressed
        btDetalleArrComplet.setEnabled(true);
    }//GEN-LAST:event_tablaArriendosListosMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dialogArriendosCompletados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dialogArriendosCompletados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dialogArriendosCompletados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dialogArriendosCompletados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                dialogArriendosCompletados dialog = new dialogArriendosCompletados(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDetalleArrComplet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaArriendosListos;
    private javax.swing.JTextField txtBuscadorArrTerminados;
    // End of variables declaration//GEN-END:variables
}
