/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package arriendos;
import inicio.ModeloTablaDTM;
import java.awt.Color;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.util.SystemOutLogger;

/**
 *
 * @author GabrielNote
 */
public class dialogAgregarProdArr extends javax.swing.JDialog {
    
ArrayList listaidproductos = new ArrayList();        
    
SQLArriendo sqlarriendo = new SQLArriendo();
Arriendo arriendoclase = new Arriendo();

Icon iconoAlerta  =  new ImageIcon("C:/Sistema Muninn/Imagenes/alertaIcono.png");
Icon iconoBueno  =  new ImageIcon("C:/Sistema Muninn/Imagenes/aceptadoIcono.png");
Icon iconoError  =  new ImageIcon("C:/Sistema Muninn/Imagenes//errorIcono.png");
Icon iconoInfo  =  new ImageIcon("C:/Sistema Muninn/Imagenes/infoIcono.png"); 
    /**
     * Creates new form JDAddProdArr
     */
    public dialogAgregarProdArr( javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        
        sqlarriendo.tablaTodosProd.addColumn("ID");
        sqlarriendo.tablaTodosProd.addColumn("Producto");
          
 

    }

    /** 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductosAdd = new javax.swing.JTable();
        txtBuscadorProd = new javax.swing.JTextField();
        lbValorGarant1 = new javax.swing.JLabel();
        lbValorGarant2 = new javax.swing.JLabel();
        cbCategorias = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lbValorArr1 = new javax.swing.JLabel();
        lbValorArr = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbValorArr2 = new javax.swing.JLabel();
        lbValorGarant = new javax.swing.JLabel();
        lbCantidadBod = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaProductoDescrp = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbCodProdSelec = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbFotoProd = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCantidadProd = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        btIngresarProducto = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btIngresarProducto1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MUNINN - Agregar Productos al Nuevo Arriendo");
        setIconImage(null);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(153, 153, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(38, 87, 163));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(19, 60, 124)));
        jPanel2.setOpaque(false);

        tablaProductosAdd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaProductosAdd.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaProductosAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProductosAddMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaProductosAddMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tablaProductosAdd);

        txtBuscadorProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscadorProdKeyReleased(evt);
            }
        });

        lbValorGarant1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbValorGarant1.setForeground(new java.awt.Color(255, 255, 255));
        lbValorGarant1.setText("Buscador por ID, Marca o Descripción");

        lbValorGarant2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbValorGarant2.setForeground(new java.awt.Color(255, 255, 255));
        lbValorGarant2.setText("Filtro por Categorias");

        cbCategorias.setBackground(new java.awt.Color(65, 85, 128));
        cbCategorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbCategoriasMouseClicked(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(65, 85, 128));
        jButton1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Actualizar Filtro");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbValorGarant1)
                    .addComponent(txtBuscadorProd, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(lbValorGarant2)
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cbCategorias, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbValorGarant1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscadorProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbValorGarant2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.add(jPanel2);
        jPanel2.setBounds(20, 20, 320, 440);

        jPanel3.setBackground(new java.awt.Color(38, 87, 163));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(19, 60, 124)));
        jPanel3.setMinimumSize(new java.awt.Dimension(541, 244));
        jPanel3.setOpaque(false);

        jPanel7.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel7.setOpaque(false);

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Valor Unitario de Arriendo por Dia");

        lbValorArr1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbValorArr1.setForeground(new java.awt.Color(255, 255, 255));
        lbValorArr1.setText("$");

        lbValorArr.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbValorArr.setForeground(new java.awt.Color(255, 255, 255));
        lbValorArr.setText("No ha seleccionado nada");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Valor Unitario de Garantia");

        lbValorArr2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbValorArr2.setForeground(new java.awt.Color(255, 255, 255));
        lbValorArr2.setText("$");

        lbValorGarant.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbValorGarant.setForeground(new java.awt.Color(255, 255, 255));
        lbValorGarant.setText("No ha seleccionado nada");

        lbCantidadBod.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lbCantidadBod.setForeground(new java.awt.Color(255, 255, 255));
        lbCantidadBod.setText("No ha seleccionado nada");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cantidad Disponible");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbValorArr2)
                            .addComponent(lbValorArr1))))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbValorArr)
                    .addComponent(lbValorGarant)
                    .addComponent(lbCantidadBod, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbValorArr1)
                    .addComponent(lbValorArr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lbValorArr2)
                    .addComponent(lbValorGarant))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCantidadBod)
                    .addComponent(jLabel3))
                .addContainerGap())
        );

        jPanel8.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel8.setOpaque(false);

        txtaProductoDescrp.setBackground(new java.awt.Color(219, 228, 235));
        txtaProductoDescrp.setColumns(20);
        txtaProductoDescrp.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtaProductoDescrp.setRows(5);
        txtaProductoDescrp.setText("No ah seleccionado nada\n");
        txtaProductoDescrp.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtaProductoDescrp.setEnabled(false);
        jScrollPane2.setViewportView(txtaProductoDescrp);

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Producto: ");

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ID:");

        lbCodProdSelec.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbCodProdSelec.setForeground(new java.awt.Color(255, 255, 255));
        lbCodProdSelec.setText("Id Producto");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(lbCodProdSelec, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lbCodProdSelec))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 59, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 122, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.add(jPanel3);
        jPanel3.setBounds(350, 20, 440, 240);

        jPanel1.setBackground(new java.awt.Color(38, 87, 163));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(19, 60, 124)));
        jPanel1.setOpaque(false);

        lbFotoProd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbFotoProd, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbFotoProd, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.add(jPanel1);
        jPanel1.setBounds(800, 30, 360, 299);

        jPanel4.setBackground(new java.awt.Color(38, 87, 163));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(19, 60, 124)));
        jPanel4.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cantidad a Arrendar");

        txtCantidadProd.setBackground(new java.awt.Color(255, 255, 204));
        txtCantidadProd.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        txtCantidadProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadProdKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 266, Short.MAX_VALUE))
                    .addComponent(txtCantidadProd))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCantidadProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel4);
        jPanel4.setBounds(350, 268, 440, 80);

        jPanel6.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel6.setOpaque(false);

        btIngresarProducto.setBackground(new java.awt.Color(65, 85, 128));
        btIngresarProducto.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        btIngresarProducto.setForeground(new java.awt.Color(255, 255, 255));
        btIngresarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoNuevo.png"))); // NOI18N
        btIngresarProducto.setText("Ingresar Producto ");
        btIngresarProducto.setEnabled(false);
        btIngresarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIngresarProductoActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ingreso de Productos");

        btIngresarProducto1.setBackground(new java.awt.Color(65, 85, 128));
        btIngresarProducto1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        btIngresarProducto1.setForeground(new java.awt.Color(255, 255, 255));
        btIngresarProducto1.setText("Cerrar Ventana");
        btIngresarProducto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIngresarProducto1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btIngresarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btIngresarProducto1, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(20, 20, 20))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(btIngresarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btIngresarProducto1)
                    .addComponent(jLabel4))
                .addGap(15, 15, 15))
        );

        jPanel5.add(jPanel6);
        jPanel6.setBounds(350, 350, 820, 110);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoArriendos3.png"))); // NOI18N
        jPanel5.add(jLabel8);
        jLabel8.setBounds(0, 0, 1250, 520);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 1188, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscadorProdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscadorProdKeyReleased
        String buscador = txtBuscadorProd.getText();
        
        llenarListCombo();
        
        Object categ = cbCategorias.getSelectedItem();        
        sqlarriendo.buscarProductoCargaForm(categ);
        
        sqlarriendo.buscarProductoConCombobox(buscador, categ);
        tablaProductosAdd.setModel(sqlarriendo.tablaTodosProd);
    }//GEN-LAST:event_txtBuscadorProdKeyReleased

    private void tablaProductosAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProductosAddMouseClicked

    }//GEN-LAST:event_tablaProductosAddMouseClicked

    private void btIngresarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIngresarProductoActionPerformed
 int rows = tablaProductosAdd.getRowCount();
        if(validarCamposNProdl())
                {
        if(rows > 0)
        {
            if(!lbCodProdSelec.getText().equals(""))
            { //ffffff
                
                int cantidadBodega = Integer.parseInt(lbCantidadBod.getText());
                int cantidadIngres = Integer.parseInt(txtCantidadProd.getText());
                
                if(cantidadBodega>=cantidadIngres)
                {
                
                    if(tablaProductoIngr.getRowCount()==0)
                    {
                        AgregarNuevoProductoAArr();
                    }
                    else
                    {
                     System.out.print("Boton press \n");
        int IdProductoVentana = Integer.parseInt(lbCodProdSelec.getText().toString());
        int CantidadFilasTabla = tablaProductoIngr.getRowCount();
        
        int CantidadProdTabla=0;
        int IdProductoTabla =0;
        
        int contador = 0;
        
        System.out.print(" IdProducto para comprarar: "+lbCodProdSelec.getText()+" \n");
        System.out.print(" while(contador!=CantidadFilasTabla): "+contador+"!="+CantidadFilasTabla+" \n");
        while(contador<CantidadFilasTabla)
        {
            System.out.print("\nEntrando al While \n");
            System.out.print("Valor Contador: "+contador+"\n");
           
            IdProductoTabla = Integer.parseInt(tablaProductoIngr.getValueAt(contador, 0).toString());
            CantidadProdTabla = Integer.parseInt(tablaProductoIngr.getValueAt(contador, 2).toString());
            
             if(IdProductoTabla==IdProductoVentana)
            {   
                //JOptionPane.showMessageDialog(rootPane, "la ");
                System.out.print("es el mismo\n");
                break;
            
            }
             else if(contador==CantidadFilasTabla-1)
             {
                  //JOptionPane.showMessageDialog(rootPane, "recorrio todas las filas no encontro igual");
                  System.out.print("recorrio todas las filas no encontro igual\n");
                  break;
             }
            contador=contador+1;
            
            //System.out.print("Contador While: "+contador+"\n");
        } 
         System.out.print("Contador While: "+contador+"\n");
         System.out.print("id prod tabla: "+IdProductoTabla+"\n");
         System.out.print("cantidadprod: "+CantidadProdTabla+"\n");
        
        if(IdProductoTabla==IdProductoVentana)
        {
            //JOptionPane.showMessageDialog(rootPane, "es el mismo");
            int CantidadParaSumar = Integer.parseInt(txtCantidadProd.getText()); 
            int Suma = CantidadParaSumar+ CantidadProdTabla;
            tablaProductoIngr.setValueAt(Suma, contador, 2);
            JOptionPane.showMessageDialog(rootPane, "El producto "+txtaProductoDescrp.getText()+" ya habia sido agregado \n"
                    + "anteriormente, la cantidad de "+txtCantidadProd.getText()+" sera sumada.","Notificación", JOptionPane.PLAIN_MESSAGE, iconoInfo);
            
             int CantidadBodega= Integer.parseInt(lbCantidadBod.getText());
                    int CantidadIngresada = Integer.parseInt(txtCantidadProd.getText());
                    
                    int cantidadRestada = CantidadBodega-CantidadIngresada;
                    
                    System.out.print("Entrando al metodo de actualizacion de bodega. Numero a ingresar: "+cantidadRestada+"\n");
                    
                    sqlarriendo.actualizarcantidad(cantidadRestada,lbCodProdSelec.getText());
                    System.out.print("producto actualizado\n"); 
                    
                   
            limpiarCampos();
            
        }
        else
        {
            //JOptionPane.showMessageDialog(rootPane, "NO es el mismo");
             System.out.print("NO es el mismo, se agregara producto nuevo a la lista\n");
            AgregarNuevoProductoAArr();
        }
                    }
                }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "Atencion, agrego "+txtCantidadProd.getText()+" "
                + "producto(s) y solo hay disponible "+lbCantidadBod.getText()+"\nVuelva a ingresar","Notificación", JOptionPane.PLAIN_MESSAGE, iconoError);
                txtCantidadProd.setText("");
                txtCantidadProd.requestFocus();
            }
            }
            else
            {
            JOptionPane.showMessageDialog(rootPane, "No ah seleccionado ningun producto","Notificación", JOptionPane.PLAIN_MESSAGE, iconoAlerta);
            }
        }
        else
        {
         JOptionPane.showMessageDialog(rootPane, "No hay productos en la tabla","Notificación", JOptionPane.PLAIN_MESSAGE, iconoInfo);
        }
}      
        
    }//GEN-LAST:event_btIngresarProductoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        llenarListCombo();
        Object categ = cbCategorias.getSelectedItem();
        sqlarriendo.buscarProductoCargaForm(categ);
        tablaProductosAdd.setModel(sqlarriendo.tablaTodosProd);
        
        System.out.print("Abriendo ventana inbgreso producto\n");
        System.out.print("--------------\n");
    }//GEN-LAST:event_formWindowOpened

    private void txtCantidadProdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadProdKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c) == false) {
            evt.consume();
        }
        if(txtCantidadProd.getText().length()== 8) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCantidadProdKeyTyped

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        tablaProductosAdd.getTableHeader().setReorderingAllowed(false) ;
        
        llenarListCombo();
        
        Object categ = cbCategorias.getSelectedItem();
        
        sqlarriendo.buscarProductoCargaForm(categ);
        tablaProductosAdd.setModel(sqlarriendo.tablaTodosProd);
    }//GEN-LAST:event_formWindowActivated

    private void cbCategoriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbCategoriasMouseClicked
        
    }//GEN-LAST:event_cbCategoriasMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Object categ = cbCategorias.getSelectedItem();
        sqlarriendo.buscarProductoCargaForm(categ);
        tablaProductosAdd.setModel(sqlarriendo.tablaTodosProd);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tablaProductosAddMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProductosAddMousePressed
//btPrueba.setEnabled(true);         
        btIngresarProducto.setEnabled(true);
         int row = tablaProductosAdd.getSelectedRow();         
         String id=tablaProductosAdd.getValueAt(row, 0).toString();
        
        Image dtCat = sqlarriendo.getfoto(id);
        Image i = dtCat.getScaledInstance(340,277, Image.SCALE_AREA_AVERAGING);
        Icon icon = new ImageIcon(i);
        lbFotoProd.setIcon(icon);
         
         ArrayList datos=new ArrayList();
         datos=sqlarriendo.buscarProductoSelecc(id);
         
         lbCodProdSelec.setText(datos.get(0).toString());// aca obtengo los datos de arreglo
         txtaProductoDescrp.setText(datos.get(2).toString()+" "+ datos.get(1));
         lbCantidadBod.setText(datos.get(3).toString());
         lbValorArr.setText(datos.get(4).toString());
         lbValorGarant.setText(datos.get(5).toString());

    }//GEN-LAST:event_tablaProductosAddMousePressed

    private void btIngresarProducto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIngresarProducto1ActionPerformed
        int mensaje= JOptionPane.showConfirmDialog(rootPane, " ¿Confirma cerrar esta Ventana? \n No se quitaran los Productos Agregados Anteriormente", "\tConfirmación",
    JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,iconoAlerta);

     if(mensaje==JOptionPane.YES_NO_OPTION)
            {
            this.dispose();
            }
    }//GEN-LAST:event_btIngresarProducto1ActionPerformed
 

public boolean validarCamposNProdl()
    {
    boolean respuesta=true;
    String variable1 = "";
    if(txtCantidadProd.getText().equals(""))
                {
                
                variable1=variable1+ "Debe ingresar una cantidad\n";
                respuesta=false;
                txtCantidadProd.requestFocus();
                }
    else if(txtCantidadProd.getText().equals("0"))
                {
                
                variable1=variable1+ "Cantidad no Valida\n";
                respuesta=false;
                txtCantidadProd.setText("");
                txtCantidadProd.requestFocus();
                }

     if(!respuesta)
    {
      JOptionPane.showMessageDialog(rootPane, variable1,  "Notificación", JOptionPane.PLAIN_MESSAGE, iconoAlerta);
        }
    return respuesta;
    }

////////////////////////////////////////////////////

public void llenarListCombo()
{
   
   sqlarriendo.llenarComboCategorias();
   cbCategorias.setModel(sqlarriendo.comboCategoriasFiltro);         
   
}


void AgregarNuevoProductoAArr()
{
     System.out.print("AgregarNuevoProductoAArr\n");
        int cantidadIngres = Integer.parseInt(txtCantidadProd.getText());
            Object []filanew= new Object[5];
                    String id = lbCodProdSelec.getText();
                    String descp= txtaProductoDescrp.getText();
                    String valorA = lbValorArr.getText();
                    String valorP = lbValorGarant.getText();
                    String cantid = txtCantidadProd.getText();
    
                    //multiplicacion precio garantia
                    int valorgarantia= Integer.parseInt(valorP);
                    int totalGarantia = valorgarantia*cantidadIngres;
    
                    //multiplicacion precio garantia
                    int valorArriendo= Integer.parseInt(valorA);
                    int totalProducto = valorArriendo*cantidadIngres;
                    
                    filanew[0]=id;
                    filanew[1]=descp; 
                    filanew[2]=cantid;
                    filanew[3]=totalGarantia;
                    filanew[4]=totalProducto;     
                    tablaProductoIngr.addRow(filanew);
                    
                    int CantidadBodega= Integer.parseInt(lbCantidadBod.getText());
                    int CantidadIngresada = Integer.parseInt(txtCantidadProd.getText());
                    
                    int cantidadRestada = CantidadBodega-CantidadIngresada;
                    
                    System.out.print("Entrando al metodo de actualizacion de bodega. Numero a ingresar: "+cantidadRestada+"\n");
                    sqlarriendo.actualizarcantidad(cantidadRestada,id);
                    System.out.print("producto actualizado\n"); 
                    
                    JOptionPane.showMessageDialog(rootPane, "El Producto a sido Agregado a la lista","Notificación", JOptionPane.PLAIN_MESSAGE, iconoBueno);
                    System.out.print("Actualizo Producto\n");
                    
                    int mensaje= JOptionPane.showConfirmDialog(rootPane, "¿Desea Agregar Otro Producto??", "\tConfirmacion",
                    JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,iconoAlerta);
                    
                    
                    if(mensaje==JOptionPane.YES_NO_OPTION)
                    {
                        System.out.print("\nSe eligio agregar otro producto NuevoProducto\n");
                        limpiarCampos();
                       
                    }
                    
                    else{
                        this.dispose();
                        }


}


void limpiarCampos()
{
ImageIcon foto=new ImageIcon(" ");
Icon icono=new ImageIcon(foto.getImage().getScaledInstance(lbFotoProd.getWidth(), lbFotoProd.getHeight(),Image.SCALE_DEFAULT));
lbFotoProd.setIcon(icono);
txtaProductoDescrp.setText("");
txtBuscadorProd.setText("");
txtCantidadProd.setText("");
lbValorArr.setText("");
lbValorGarant.setText("");
lbCantidadBod.setText("");
lbCodProdSelec.setText("");


}


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dialogAgregarProdArr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dialogAgregarProdArr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dialogAgregarProdArr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dialogAgregarProdArr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                dialogAgregarProdArr dialog = new dialogAgregarProdArr(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btIngresarProducto;
    private javax.swing.JButton btIngresarProducto1;
    private javax.swing.JComboBox cbCategorias;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbCantidadBod;
    private javax.swing.JLabel lbCodProdSelec;
    private javax.swing.JLabel lbFotoProd;
    private javax.swing.JLabel lbValorArr;
    private javax.swing.JLabel lbValorArr1;
    private javax.swing.JLabel lbValorArr2;
    private javax.swing.JLabel lbValorGarant;
    private javax.swing.JLabel lbValorGarant1;
    private javax.swing.JLabel lbValorGarant2;
    private javax.swing.JTable tablaProductosAdd;
    private javax.swing.JTextField txtBuscadorProd;
    private javax.swing.JTextField txtCantidadProd;
    private javax.swing.JTextArea txtaProductoDescrp;
    // End of variables declaration//GEN-END:variables
DefaultTableModel tablaProductoIngr= (DefaultTableModel)dialogNuevoArriendo.tablaProductosArr.getModel();  
//ModeloTablaDTM tablaProductoIngr = (ModeloTablaDTM)dialogNuevoArriendo.tablaProductosArr.getModel();  
}

