
package arriendos;
import java.awt.Color;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author GabrielNote
 */
public class dialogVerProdArr extends javax.swing.JDialog {
Arriendo arriendo = new Arriendo();
Icon iconoAlerta  =  new ImageIcon("C:/Sistema Muninn/Imagenes/alertaIcono.png");
Icon iconoBueno  =  new ImageIcon("C:/Sistema Muninn/Imagenes/aceptadoIcono.png");
Icon iconoError  =  new ImageIcon("C:/Sistema Muninn/Imagenes//errorIcono.png");
Icon iconoInfo  =  new ImageIcon("C:/Sistema Muninn/Imagenes/infoIcono.png"); 
//  ,"Notificación", JOptionPane.PLAIN_MESSAGE, iconoError);
SQLArriendo sqlarriendo = new SQLArriendo();
    /**
     * Creates new form JDAddProdArr
     */
    public dialogVerProdArr( javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbCodProdSelec = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbValorGarant = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaProductoDescrp = new javax.swing.JTextArea();
        lbHorasArr = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbValorArr2 = new javax.swing.JLabel();
        lbValorArr1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbValorArr = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCantidadProdDev = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lbCantidadEntregada = new javax.swing.JLabel();
        btIngresarProducto = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MUNINN - Comprobador de Cantidad devuelta por Producto");
        setIconImage(null);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.setLayout(null);

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setOpaque(false);

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Verificador de Cantidad por Producto");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(211, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1);
        jPanel1.setBounds(11, 12, 591, 54);

        jPanel3.setBackground(new java.awt.Color(38, 87, 163));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(19, 60, 124)));

        lbCodProdSelec.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lbCodProdSelec.setForeground(new java.awt.Color(255, 255, 255));
        lbCodProdSelec.setText("Valor");

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ID Producto");

        lbValorGarant.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbValorGarant.setForeground(new java.awt.Color(255, 255, 255));
        lbValorGarant.setText("Mostrar Valor de Producto Costo");

        txtaProductoDescrp.setBackground(new java.awt.Color(219, 228, 235));
        txtaProductoDescrp.setColumns(20);
        txtaProductoDescrp.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtaProductoDescrp.setRows(5);
        txtaProductoDescrp.setText("Valor\n");
        txtaProductoDescrp.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtaProductoDescrp.setEnabled(false);
        jScrollPane2.setViewportView(txtaProductoDescrp);

        lbHorasArr.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbHorasArr.setForeground(new java.awt.Color(255, 255, 255));
        lbHorasArr.setText("5");

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Producto: ");

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Cantidad de Horas");

        lbValorArr2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbValorArr2.setForeground(new java.awt.Color(255, 255, 255));
        lbValorArr2.setText("$");

        lbValorArr1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbValorArr1.setForeground(new java.awt.Color(255, 255, 255));
        lbValorArr1.setText("$");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Valor Unitario de Garantia:");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Valor Unitario de Arriendo por Hora:");

        lbValorArr.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbValorArr.setForeground(new java.awt.Color(255, 255, 255));
        lbValorArr.setText("Mostrar Valor de Producto Arriendo");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCodProdSelec)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lbValorArr1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbValorArr))
                            .addComponent(lbHorasArr)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lbValorArr2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbValorGarant)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lbCodProdSelec))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbHorasArr)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbValorArr)
                        .addComponent(lbValorArr1))
                    .addComponent(jLabel5))
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lbValorArr2)
                    .addComponent(lbValorGarant))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(11, 72, 591, 220);

        jPanel4.setBackground(new java.awt.Color(38, 87, 163));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(19, 60, 124)));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cantidad Devuelta");

        txtCantidadProdDev.setBackground(new java.awt.Color(255, 255, 204));
        txtCantidadProdDev.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        txtCantidadProdDev.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadProdDevKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cantidad Entregada:");

        lbCantidadEntregada.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lbCantidadEntregada.setForeground(new java.awt.Color(255, 255, 255));
        lbCantidadEntregada.setText("6");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCantidadEntregada)
                    .addComponent(txtCantidadProdDev, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbCantidadEntregada))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantidadProdDev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4);
        jPanel4.setBounds(10, 300, 591, 100);

        btIngresarProducto.setBackground(new java.awt.Color(65, 85, 128));
        btIngresarProducto.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        btIngresarProducto.setForeground(new java.awt.Color(255, 255, 255));
        btIngresarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/terminar.png"))); // NOI18N
        btIngresarProducto.setText("Producto Verificado");
        btIngresarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIngresarProductoActionPerformed(evt);
            }
        });
        jPanel2.add(btIngresarProducto);
        btIngresarProducto.setBounds(10, 420, 591, 60);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoArriendos2.png"))); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(0, 0, 660, 550);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btIngresarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIngresarProductoActionPerformed
        if(!txtCantidadProdDev.getText().equals(""))
        {
                    int horasTotales = Integer.parseInt(lbHorasArr.getText());
        
                    Object []filanew= new Object[6];
                    String id = lbCodProdSelec.getText(); //id producto
                    String descp= txtaProductoDescrp.getText(); //nombre producto
                    String valorA = lbValorArr.getText(); //arriendo unit
                    String valorGarant = lbValorGarant.getText(); //garantia unit                  
                    
                    int ValorGarantia = Integer.parseInt(valorGarant);
                    int ValorArrHr = Integer.parseInt(valorA);
                    
                    int cInic = Integer.parseInt(lbCantidadEntregada.getText());//cantidad inicial
                    System.out.print("Cantidad Entregada: "+cInic+"\n");
                    
                    int cFin = Integer.parseInt(txtCantidadProdDev.getText());// cantidad entreg
                    System.out.print("Total Devuelta: "+cFin+"\n");
                    
                    //valor garanti por numero resultante a resta entre cantidad entrgada y cantidad dev
                    
                    int resultadoRest = cInic-cFin;
                    int garantia = resultadoRest*ValorGarantia;
                    int TotalArrxProd = ValorArrHr*cInic;
                    int totarriendos1 = TotalArrxProd*horasTotales; //total arriendo mas suma de horas
                    
                    System.out.print("Total Arr 000: "+cFin+"\n");
                    
                    
                    System.out.print("Total Arr 000: "+cFin+"\n");
                    System.out.print("Total Arr 000: "+TotalArrxProd+"\n");
                    System.out.print("Total Arr 001: "+totarriendos1+"\n");
                    
                    if(cInic>=cFin)
                    {
                        
                        filanew[0]=id;
                        filanew[1]=descp;
                        filanew[2]=cFin; 
                        filanew[3]=TotalArrxProd; 
                        filanew[4]=garantia;
                        filanew[5]=totarriendos1; 
                        
                        System.out.print("Cantidad Actulizada ingresada: "+cFin+"\n"); 
                        
                        tablaProductoFinArr.addRow(filanew); 
                    
                    JOptionPane.showMessageDialog(rootPane, "Producto (ID "+id+") Verificado Correctamente","Notificación", JOptionPane.PLAIN_MESSAGE, iconoInfo);
                    this.dispose();
                    
                    }else
                    {
                        JOptionPane.showMessageDialog(rootPane, "Error: Ud ingreso "+cFin+" producto(s) devueltos, \n"
                                + "Pero solo se entregaron "+cInic+" producto(s)","Notificación", JOptionPane.PLAIN_MESSAGE, iconoError);
                        txtCantidadProdDev.setText("");
                        txtCantidadProdDev.requestFocus();
                    }
                       
        }
        else
        {
        JOptionPane.showMessageDialog(rootPane, "Ingrese Cantidad del Producto devuelto","Notificación", JOptionPane.PLAIN_MESSAGE, iconoAlerta);
        }
    }//GEN-LAST:event_btIngresarProductoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.setDefaultCloseOperation(0);
        JOptionPane.showMessageDialog(rootPane, "Esta ventana no se puede cerrar \n Continue con el proceso de Verificacion","Notificación", JOptionPane.PLAIN_MESSAGE, iconoInfo);
        txtCantidadProdDev.requestFocus();
    }//GEN-LAST:event_formWindowClosing

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void txtCantidadProdDevKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadProdDevKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c) == false) {
            evt.consume();
        }
        if(txtCantidadProdDev.getText().length()== 8) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCantidadProdDevKeyTyped

   
    

public boolean validarCamposNProdl()
    {
    boolean respuesta=true;
    String variable1 = "";
    if(txtCantidadProdDev.getText().equals(""))
                {
                
                variable1=variable1+ "- Debe ingresar una cantidad\n";
                respuesta=false;
                txtCantidadProdDev.requestFocus();
                }
    if(lbCodProdSelec.getText().equals("No ha seleccionado nada"))
                {
                variable1= variable1 + "- Seleccione un Producto\n";
                lbCodProdSelec.requestFocus();
                respuesta=false;
                }

     if(!respuesta)
    {
      JOptionPane.showMessageDialog(rootPane, variable1,"Notificación", JOptionPane.PLAIN_MESSAGE, iconoAlerta);
        }
    return respuesta;
    }

////////////////////////////////////////////////////

    




    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dialogVerProdArr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dialogVerProdArr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dialogVerProdArr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dialogVerProdArr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                dialogVerProdArr dialog = new dialogVerProdArr(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btIngresarProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JLabel lbCantidadEntregada;
    public static javax.swing.JLabel lbCodProdSelec;
    public static javax.swing.JLabel lbHorasArr;
    public static javax.swing.JLabel lbValorArr;
    private javax.swing.JLabel lbValorArr1;
    private javax.swing.JLabel lbValorArr2;
    public static javax.swing.JLabel lbValorGarant;
    private javax.swing.JTextField txtCantidadProdDev;
    public static javax.swing.JTextArea txtaProductoDescrp;
    // End of variables declaration//GEN-END:variables
DefaultTableModel tablaProductoFinArr= (DefaultTableModel)dialogFinArriendo.tablaProductosFinArr.getModel();  
}

