/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package inicio;

//import com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl;
import conexion.ConexionBD;
import java.awt.Color;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author Gabriel
 */
public class ventanaLogin extends javax.swing.JFrame {
    
ConexionBD conexionbd = new ConexionBD();
SQLUsuario sqlusuario = new SQLUsuario();

Icon iconoAlerta  =  new ImageIcon("C:/Sistema Muninn/Imagenes/alertaIcono.png");
Icon iconoBueno  =  new ImageIcon("C:/Sistema Muninn/Imagenes/aceptadoIcono.png");
Icon iconoError  =  new ImageIcon("C:/Sistema Muninn/Imagenes//errorIcono.png");
Icon iconoInfo  =  new ImageIcon("C:/Sistema Muninn/Imagenes/infoIcono.png"); 
//  ,"Notificación", JOptionPane.PLAIN_MESSAGE, iconoError);  

private int x; //Posicion del mouse
private int y;//Posicion del mouse

private splash splashframe;

//Metodo para asignar el texto del splash
public ventanaLogin(splash splashFrame) 
{
    this.splashframe=splashFrame;
    setProgress(0, "Iniciando Carga del sistema");
    initComponents();
    setProgress(20, "Obteniendo recursos graficos");
    setProgress(40, "Cargando Librerias internas");
    setProgress(70, "Cargando con la Base de Datos");
    setProgress(80, "Iniciando ventana de Login");
    setProgress(100, "Carga Completada");
    this.setLocationRelativeTo(null);
    
    
}
private void setProgress(int percent, String informacion){
splashframe.getJLabel().setText(informacion);//envia texto al label de cargando
splashframe.getJProgressBar().setValue(percent);//envia el porcentaje de carga de la barra

    try {
        Thread.sleep(300); //Tiempo del splash
    } catch (InterruptedException ex) {
        JOptionPane.showMessageDialog(rootPane, "Error al Cargar SPL01","Notificación", JOptionPane.PLAIN_MESSAGE, iconoError);  
    }

}

    public ventanaLogin() {
        initComponents();        
        setLocationRelativeTo(null);
        setResizable(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsuario = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        btEntrar = new javax.swing.JButton();
        btCerrar1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MUNINN - Accesi de Usuario");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagenes/miniLogo.png")).getImage());
        setUndecorated(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsuario.setBackground(new java.awt.Color(255, 255, 204));
        txtUsuario.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyReleased(evt);
            }
        });
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 160, 30));

        Password.setBackground(new java.awt.Color(255, 255, 204));
        Password.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        Password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PasswordKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PasswordKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PasswordKeyTyped(evt);
            }
        });
        getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 160, 30));

        btEntrar.setBackground(new java.awt.Color(171, 149, 84));
        btEntrar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btEntrar.setText("Entrar");
        btEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(btEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 150, 40));

        btCerrar1.setBackground(new java.awt.Color(171, 149, 84));
        btCerrar1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btCerrar1.setText("Cerrar");
        btCerrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCerrar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btCerrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 120, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventanaLogin.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEntrarActionPerformed
      if(VerificarCamposProd())
      {
        String nomb = txtUsuario.getText();
        String pass = new String (Password.getPassword());
        
        String buscaaaCuenta = sqlusuario.existeCuentaUser(nomb, pass);

        if (buscaaaCuenta.equals(""))
           { 
            JOptionPane.showMessageDialog(rootPane, "Nombre o Contraseña incorrecto, verifique","Notificación", JOptionPane.PLAIN_MESSAGE, iconoError);  
            txtUsuario.setBackground(new Color (255,255,204));
            Password.setBackground(new Color (255,255,204));
           }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "Usuario Correcto\nBienvenido "+txtUsuario.getText(),"Notificación", JOptionPane.PLAIN_MESSAGE, iconoBueno);  
           inicioRapido inicior = new inicioRapido();
            inicior.setVisible(true);
            inicior.lbNombreUusario.setText(txtUsuario.getText());
            dispose();
            
            
            
        }
        
      }
    }//GEN-LAST:event_btEntrarActionPerformed

    private void txtUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyReleased
        String valor = txtUsuario.getText();        
        if(valor.equals(""))        {
            txtUsuario.setBackground(new Color (255,255,204));
        }
        else        {
            txtUsuario.setBackground(new Color (255,255,255));
        }
    }//GEN-LAST:event_txtUsuarioKeyReleased

    private void PasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordKeyReleased
        String valor = Password.getText();        
        if(valor.equals(""))        {
            Password.setBackground(new Color (255,255,204));
        }
        else        {
            Password.setBackground(new Color (255,255,255));
        }
        
       
    }//GEN-LAST:event_PasswordKeyReleased

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int n= JOptionPane.showConfirmDialog(rootPane, "¿Desea Salir?", "Confirmación",
        JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,iconoAlerta);
        if(n==JOptionPane.YES_NO_OPTION){
        System.exit(0);}
        else{
        this.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);}
    }//GEN-LAST:event_formWindowClosing

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
         Point ubicacion = MouseInfo.getPointerInfo().getLocation();//1
   // System.out.println("Coordenadas: ("+ubicacion.x+","+ubicacion.y+")");//2
    setLocation(ubicacion.x - x, ubicacion.y - y);//3
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        x = evt.getX(); 
        y = evt.getY(); 

    }//GEN-LAST:event_formMousePressed

    private void btCerrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCerrar1ActionPerformed
        int n= JOptionPane.showConfirmDialog(rootPane, "¿Desea cerrar la Aplicación?", "Confirmación",
        JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,iconoAlerta);
        if(n==JOptionPane.YES_NO_OPTION){
        System.exit(0);}
        else{
        this.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);}
    }//GEN-LAST:event_btCerrar1ActionPerformed

    private void PasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordKeyTyped
        
   
    }//GEN-LAST:event_PasswordKeyTyped

    private void PasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordKeyPressed
        char car=(char) evt.getKeyCode();
        if(car==evt.VK_ENTER){
            if(VerificarCamposProd())
      {
        String nomb = txtUsuario.getText();
        String pass = new String (Password.getPassword());
        
        String buscaaaCuenta = sqlusuario.existeCuentaUser(nomb, pass);

        if (buscaaaCuenta.equals(""))
           { 
            JOptionPane.showMessageDialog(rootPane, "Nombre o Contraseña incorrecto, verifique","Notificación", JOptionPane.PLAIN_MESSAGE, iconoError);  
            txtUsuario.setBackground(new Color (255,255,204));
            Password.setBackground(new Color (255,255,204));
            Password.setText("");
            Password.requestFocus();
           }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "Usuario Correcto\nBienvenido "+txtUsuario.getText(),"Notificación", JOptionPane.PLAIN_MESSAGE, iconoBueno);  
           inicioRapido inicior = new inicioRapido();
            inicior.setVisible(true);
            inicior.lbNombreUusario.setText(txtUsuario.getText());
            dispose();
            
            
            
        }
        
      }
        }
    }//GEN-LAST:event_PasswordKeyPressed

    
public boolean VerificarCamposProd ()
{
    boolean respuesta=true;
    String variable1 = "";
    if(txtUsuario.getText().equals(""))
                {
                
                variable1=variable1+ "Debe ingresar el Usuario \n";
                respuesta=false;
                txtUsuario.requestFocus();
                }
    else if(Password.getText().equals(""))
                {
                
                variable1=variable1+ "Debe ingresar la contraseña \n";
                respuesta=false;
                Password.requestFocus();
                }
       if(!respuesta)
    {
      JOptionPane.showMessageDialog(rootPane, variable1,  "Notificación", JOptionPane.PLAIN_MESSAGE, iconoAlerta);
        }
    
    return respuesta;
    
}    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ventanaLogin().setVisible(true);
                System.out.print("Frame de Login iniciado...s \n");
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Password;
    private javax.swing.JButton btCerrar1;
    private javax.swing.JButton btEntrar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
